
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ClientAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ClientAccount
 * 
 */
export type ClientAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$ClientAccountPayload>

export type AggregateClientAccount = {
  _count: ClientAccountCountAggregateOutputType | null
  _avg: ClientAccountAvgAggregateOutputType | null
  _sum: ClientAccountSumAggregateOutputType | null
  _min: ClientAccountMinAggregateOutputType | null
  _max: ClientAccountMaxAggregateOutputType | null
}

export type ClientAccountAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type ClientAccountSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type ClientAccountMinAggregateOutputType = {
  id: number | null
  userId: number | null
  firstName: string | null
  lastName: string | null
  contactNumber: string | null
  email: string | null
}

export type ClientAccountMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  firstName: string | null
  lastName: string | null
  contactNumber: string | null
  email: string | null
}

export type ClientAccountCountAggregateOutputType = {
  id: number
  userId: number
  firstName: number
  lastName: number
  contactNumber: number
  email: number
  _all: number
}


export type ClientAccountAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type ClientAccountSumAggregateInputType = {
  id?: true
  userId?: true
}

export type ClientAccountMinAggregateInputType = {
  id?: true
  userId?: true
  firstName?: true
  lastName?: true
  contactNumber?: true
  email?: true
}

export type ClientAccountMaxAggregateInputType = {
  id?: true
  userId?: true
  firstName?: true
  lastName?: true
  contactNumber?: true
  email?: true
}

export type ClientAccountCountAggregateInputType = {
  id?: true
  userId?: true
  firstName?: true
  lastName?: true
  contactNumber?: true
  email?: true
  _all?: true
}

export type ClientAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientAccount to aggregate.
   */
  where?: Prisma.ClientAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAccounts to fetch.
   */
  orderBy?: Prisma.ClientAccountOrderByWithRelationInput | Prisma.ClientAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClientAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ClientAccounts
  **/
  _count?: true | ClientAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClientAccountAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClientAccountSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClientAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClientAccountMaxAggregateInputType
}

export type GetClientAccountAggregateType<T extends ClientAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateClientAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClientAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateClientAccount[P]>
}




export type ClientAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClientAccountWhereInput
  orderBy?: Prisma.ClientAccountOrderByWithAggregationInput | Prisma.ClientAccountOrderByWithAggregationInput[]
  by: Prisma.ClientAccountScalarFieldEnum[] | Prisma.ClientAccountScalarFieldEnum
  having?: Prisma.ClientAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClientAccountCountAggregateInputType | true
  _avg?: ClientAccountAvgAggregateInputType
  _sum?: ClientAccountSumAggregateInputType
  _min?: ClientAccountMinAggregateInputType
  _max?: ClientAccountMaxAggregateInputType
}

export type ClientAccountGroupByOutputType = {
  id: number
  userId: number
  firstName: string
  lastName: string
  contactNumber: string
  email: string
  _count: ClientAccountCountAggregateOutputType | null
  _avg: ClientAccountAvgAggregateOutputType | null
  _sum: ClientAccountSumAggregateOutputType | null
  _min: ClientAccountMinAggregateOutputType | null
  _max: ClientAccountMaxAggregateOutputType | null
}

type GetClientAccountGroupByPayload<T extends ClientAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClientAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClientAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClientAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClientAccountGroupByOutputType[P]>
      }
    >
  >



export type ClientAccountWhereInput = {
  AND?: Prisma.ClientAccountWhereInput | Prisma.ClientAccountWhereInput[]
  OR?: Prisma.ClientAccountWhereInput[]
  NOT?: Prisma.ClientAccountWhereInput | Prisma.ClientAccountWhereInput[]
  id?: Prisma.IntFilter<"ClientAccount"> | number
  userId?: Prisma.IntFilter<"ClientAccount"> | number
  firstName?: Prisma.StringFilter<"ClientAccount"> | string
  lastName?: Prisma.StringFilter<"ClientAccount"> | string
  contactNumber?: Prisma.StringFilter<"ClientAccount"> | string
  email?: Prisma.StringFilter<"ClientAccount"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  appointments?: Prisma.AppointmentListRelationFilter
}

export type ClientAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  appointments?: Prisma.AppointmentOrderByRelationAggregateInput
  _relevance?: Prisma.ClientAccountOrderByRelevanceInput
}

export type ClientAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId?: number
  AND?: Prisma.ClientAccountWhereInput | Prisma.ClientAccountWhereInput[]
  OR?: Prisma.ClientAccountWhereInput[]
  NOT?: Prisma.ClientAccountWhereInput | Prisma.ClientAccountWhereInput[]
  firstName?: Prisma.StringFilter<"ClientAccount"> | string
  lastName?: Prisma.StringFilter<"ClientAccount"> | string
  contactNumber?: Prisma.StringFilter<"ClientAccount"> | string
  email?: Prisma.StringFilter<"ClientAccount"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  appointments?: Prisma.AppointmentListRelationFilter
}, "id" | "userId">

export type ClientAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
  _count?: Prisma.ClientAccountCountOrderByAggregateInput
  _avg?: Prisma.ClientAccountAvgOrderByAggregateInput
  _max?: Prisma.ClientAccountMaxOrderByAggregateInput
  _min?: Prisma.ClientAccountMinOrderByAggregateInput
  _sum?: Prisma.ClientAccountSumOrderByAggregateInput
}

export type ClientAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClientAccountScalarWhereWithAggregatesInput | Prisma.ClientAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClientAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClientAccountScalarWhereWithAggregatesInput | Prisma.ClientAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ClientAccount"> | number
  userId?: Prisma.IntWithAggregatesFilter<"ClientAccount"> | number
  firstName?: Prisma.StringWithAggregatesFilter<"ClientAccount"> | string
  lastName?: Prisma.StringWithAggregatesFilter<"ClientAccount"> | string
  contactNumber?: Prisma.StringWithAggregatesFilter<"ClientAccount"> | string
  email?: Prisma.StringWithAggregatesFilter<"ClientAccount"> | string
}

export type ClientAccountCreateInput = {
  firstName: string
  lastName: string
  contactNumber: string
  email: string
  user: Prisma.UserCreateNestedOneWithoutClientInput
  appointments?: Prisma.AppointmentCreateNestedManyWithoutClientInput
}

export type ClientAccountUncheckedCreateInput = {
  id?: number
  userId: number
  firstName: string
  lastName: string
  contactNumber: string
  email: string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutClientInput
}

export type ClientAccountUpdateInput = {
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutClientNestedInput
  appointments?: Prisma.AppointmentUpdateManyWithoutClientNestedInput
}

export type ClientAccountUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutClientNestedInput
}

export type ClientAccountCreateManyInput = {
  id?: number
  userId: number
  firstName: string
  lastName: string
  contactNumber: string
  email: string
}

export type ClientAccountUpdateManyMutationInput = {
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ClientAccountUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ClientAccountNullableScalarRelationFilter = {
  is?: Prisma.ClientAccountWhereInput | null
  isNot?: Prisma.ClientAccountWhereInput | null
}

export type ClientAccountOrderByRelevanceInput = {
  fields: Prisma.ClientAccountOrderByRelevanceFieldEnum | Prisma.ClientAccountOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ClientAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type ClientAccountAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ClientAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type ClientAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type ClientAccountSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ClientAccountScalarRelationFilter = {
  is?: Prisma.ClientAccountWhereInput
  isNot?: Prisma.ClientAccountWhereInput
}

export type ClientAccountCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ClientAccountCreateWithoutUserInput, Prisma.ClientAccountUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ClientAccountCreateOrConnectWithoutUserInput
  connect?: Prisma.ClientAccountWhereUniqueInput
}

export type ClientAccountUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ClientAccountCreateWithoutUserInput, Prisma.ClientAccountUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ClientAccountCreateOrConnectWithoutUserInput
  connect?: Prisma.ClientAccountWhereUniqueInput
}

export type ClientAccountUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ClientAccountCreateWithoutUserInput, Prisma.ClientAccountUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ClientAccountCreateOrConnectWithoutUserInput
  upsert?: Prisma.ClientAccountUpsertWithoutUserInput
  disconnect?: Prisma.ClientAccountWhereInput | boolean
  delete?: Prisma.ClientAccountWhereInput | boolean
  connect?: Prisma.ClientAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientAccountUpdateToOneWithWhereWithoutUserInput, Prisma.ClientAccountUpdateWithoutUserInput>, Prisma.ClientAccountUncheckedUpdateWithoutUserInput>
}

export type ClientAccountUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ClientAccountCreateWithoutUserInput, Prisma.ClientAccountUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ClientAccountCreateOrConnectWithoutUserInput
  upsert?: Prisma.ClientAccountUpsertWithoutUserInput
  disconnect?: Prisma.ClientAccountWhereInput | boolean
  delete?: Prisma.ClientAccountWhereInput | boolean
  connect?: Prisma.ClientAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientAccountUpdateToOneWithWhereWithoutUserInput, Prisma.ClientAccountUpdateWithoutUserInput>, Prisma.ClientAccountUncheckedUpdateWithoutUserInput>
}

export type ClientAccountCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.ClientAccountCreateWithoutAppointmentsInput, Prisma.ClientAccountUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.ClientAccountCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.ClientAccountWhereUniqueInput
}

export type ClientAccountUpdateOneRequiredWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.ClientAccountCreateWithoutAppointmentsInput, Prisma.ClientAccountUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.ClientAccountCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.ClientAccountUpsertWithoutAppointmentsInput
  connect?: Prisma.ClientAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientAccountUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.ClientAccountUpdateWithoutAppointmentsInput>, Prisma.ClientAccountUncheckedUpdateWithoutAppointmentsInput>
}

export type ClientAccountCreateWithoutUserInput = {
  firstName: string
  lastName: string
  contactNumber: string
  email: string
  appointments?: Prisma.AppointmentCreateNestedManyWithoutClientInput
}

export type ClientAccountUncheckedCreateWithoutUserInput = {
  id?: number
  firstName: string
  lastName: string
  contactNumber: string
  email: string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutClientInput
}

export type ClientAccountCreateOrConnectWithoutUserInput = {
  where: Prisma.ClientAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientAccountCreateWithoutUserInput, Prisma.ClientAccountUncheckedCreateWithoutUserInput>
}

export type ClientAccountUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.ClientAccountUpdateWithoutUserInput, Prisma.ClientAccountUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ClientAccountCreateWithoutUserInput, Prisma.ClientAccountUncheckedCreateWithoutUserInput>
  where?: Prisma.ClientAccountWhereInput
}

export type ClientAccountUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.ClientAccountWhereInput
  data: Prisma.XOR<Prisma.ClientAccountUpdateWithoutUserInput, Prisma.ClientAccountUncheckedUpdateWithoutUserInput>
}

export type ClientAccountUpdateWithoutUserInput = {
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.AppointmentUpdateManyWithoutClientNestedInput
}

export type ClientAccountUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutClientNestedInput
}

export type ClientAccountCreateWithoutAppointmentsInput = {
  firstName: string
  lastName: string
  contactNumber: string
  email: string
  user: Prisma.UserCreateNestedOneWithoutClientInput
}

export type ClientAccountUncheckedCreateWithoutAppointmentsInput = {
  id?: number
  userId: number
  firstName: string
  lastName: string
  contactNumber: string
  email: string
}

export type ClientAccountCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.ClientAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientAccountCreateWithoutAppointmentsInput, Prisma.ClientAccountUncheckedCreateWithoutAppointmentsInput>
}

export type ClientAccountUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.ClientAccountUpdateWithoutAppointmentsInput, Prisma.ClientAccountUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.ClientAccountCreateWithoutAppointmentsInput, Prisma.ClientAccountUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.ClientAccountWhereInput
}

export type ClientAccountUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.ClientAccountWhereInput
  data: Prisma.XOR<Prisma.ClientAccountUpdateWithoutAppointmentsInput, Prisma.ClientAccountUncheckedUpdateWithoutAppointmentsInput>
}

export type ClientAccountUpdateWithoutAppointmentsInput = {
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutClientNestedInput
}

export type ClientAccountUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  contactNumber?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ClientAccountCountOutputType
 */

export type ClientAccountCountOutputType = {
  appointments: number
}

export type ClientAccountCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | ClientAccountCountOutputTypeCountAppointmentsArgs
}

/**
 * ClientAccountCountOutputType without action
 */
export type ClientAccountCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccountCountOutputType
   */
  select?: Prisma.ClientAccountCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClientAccountCountOutputType without action
 */
export type ClientAccountCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentWhereInput
}


export type ClientAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  firstName?: boolean
  lastName?: boolean
  contactNumber?: boolean
  email?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  appointments?: boolean | Prisma.ClientAccount$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.ClientAccountCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientAccount"]>



export type ClientAccountSelectScalar = {
  id?: boolean
  userId?: boolean
  firstName?: boolean
  lastName?: boolean
  contactNumber?: boolean
  email?: boolean
}

export type ClientAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "firstName" | "lastName" | "contactNumber" | "email", ExtArgs["result"]["clientAccount"]>
export type ClientAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  appointments?: boolean | Prisma.ClientAccount$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.ClientAccountCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ClientAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ClientAccount"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    appointments: Prisma.$AppointmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    firstName: string
    lastName: string
    contactNumber: string
    email: string
  }, ExtArgs["result"]["clientAccount"]>
  composites: {}
}

export type ClientAccountGetPayload<S extends boolean | null | undefined | ClientAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload, S>

export type ClientAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClientAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: ClientAccountCountAggregateInputType | true
  }

export interface ClientAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ClientAccount'], meta: { name: 'ClientAccount' } }
  /**
   * Find zero or one ClientAccount that matches the filter.
   * @param {ClientAccountFindUniqueArgs} args - Arguments to find a ClientAccount
   * @example
   * // Get one ClientAccount
   * const clientAccount = await prisma.clientAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClientAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, ClientAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ClientAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClientAccountFindUniqueOrThrowArgs} args - Arguments to find a ClientAccount
   * @example
   * // Get one ClientAccount
   * const clientAccount = await prisma.clientAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClientAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClientAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAccountFindFirstArgs} args - Arguments to find a ClientAccount
   * @example
   * // Get one ClientAccount
   * const clientAccount = await prisma.clientAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClientAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, ClientAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAccountFindFirstOrThrowArgs} args - Arguments to find a ClientAccount
   * @example
   * // Get one ClientAccount
   * const clientAccount = await prisma.clientAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClientAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClientAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ClientAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClientAccounts
   * const clientAccounts = await prisma.clientAccount.findMany()
   * 
   * // Get first 10 ClientAccounts
   * const clientAccounts = await prisma.clientAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clientAccountWithIdOnly = await prisma.clientAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClientAccountFindManyArgs>(args?: Prisma.SelectSubset<T, ClientAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ClientAccount.
   * @param {ClientAccountCreateArgs} args - Arguments to create a ClientAccount.
   * @example
   * // Create one ClientAccount
   * const ClientAccount = await prisma.clientAccount.create({
   *   data: {
   *     // ... data to create a ClientAccount
   *   }
   * })
   * 
   */
  create<T extends ClientAccountCreateArgs>(args: Prisma.SelectSubset<T, ClientAccountCreateArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ClientAccounts.
   * @param {ClientAccountCreateManyArgs} args - Arguments to create many ClientAccounts.
   * @example
   * // Create many ClientAccounts
   * const clientAccount = await prisma.clientAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClientAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, ClientAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ClientAccount.
   * @param {ClientAccountDeleteArgs} args - Arguments to delete one ClientAccount.
   * @example
   * // Delete one ClientAccount
   * const ClientAccount = await prisma.clientAccount.delete({
   *   where: {
   *     // ... filter to delete one ClientAccount
   *   }
   * })
   * 
   */
  delete<T extends ClientAccountDeleteArgs>(args: Prisma.SelectSubset<T, ClientAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ClientAccount.
   * @param {ClientAccountUpdateArgs} args - Arguments to update one ClientAccount.
   * @example
   * // Update one ClientAccount
   * const clientAccount = await prisma.clientAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClientAccountUpdateArgs>(args: Prisma.SelectSubset<T, ClientAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ClientAccounts.
   * @param {ClientAccountDeleteManyArgs} args - Arguments to filter ClientAccounts to delete.
   * @example
   * // Delete a few ClientAccounts
   * const { count } = await prisma.clientAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClientAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClientAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClientAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClientAccounts
   * const clientAccount = await prisma.clientAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClientAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, ClientAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ClientAccount.
   * @param {ClientAccountUpsertArgs} args - Arguments to update or create a ClientAccount.
   * @example
   * // Update or create a ClientAccount
   * const clientAccount = await prisma.clientAccount.upsert({
   *   create: {
   *     // ... data to create a ClientAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClientAccount we want to update
   *   }
   * })
   */
  upsert<T extends ClientAccountUpsertArgs>(args: Prisma.SelectSubset<T, ClientAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ClientAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAccountCountArgs} args - Arguments to filter ClientAccounts to count.
   * @example
   * // Count the number of ClientAccounts
   * const count = await prisma.clientAccount.count({
   *   where: {
   *     // ... the filter for the ClientAccounts we want to count
   *   }
   * })
  **/
  count<T extends ClientAccountCountArgs>(
    args?: Prisma.Subset<T, ClientAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClientAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ClientAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClientAccountAggregateArgs>(args: Prisma.Subset<T, ClientAccountAggregateArgs>): Prisma.PrismaPromise<GetClientAccountAggregateType<T>>

  /**
   * Group by ClientAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClientAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClientAccountGroupByArgs['orderBy'] }
      : { orderBy?: ClientAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClientAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClientAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ClientAccount model
 */
readonly fields: ClientAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClientAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClientAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  appointments<T extends Prisma.ClientAccount$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClientAccount$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ClientAccount model
 */
export interface ClientAccountFieldRefs {
  readonly id: Prisma.FieldRef<"ClientAccount", 'Int'>
  readonly userId: Prisma.FieldRef<"ClientAccount", 'Int'>
  readonly firstName: Prisma.FieldRef<"ClientAccount", 'String'>
  readonly lastName: Prisma.FieldRef<"ClientAccount", 'String'>
  readonly contactNumber: Prisma.FieldRef<"ClientAccount", 'String'>
  readonly email: Prisma.FieldRef<"ClientAccount", 'String'>
}
    

// Custom InputTypes
/**
 * ClientAccount findUnique
 */
export type ClientAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * Filter, which ClientAccount to fetch.
   */
  where: Prisma.ClientAccountWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount findUniqueOrThrow
 */
export type ClientAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * Filter, which ClientAccount to fetch.
   */
  where: Prisma.ClientAccountWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount findFirst
 */
export type ClientAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * Filter, which ClientAccount to fetch.
   */
  where?: Prisma.ClientAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAccounts to fetch.
   */
  orderBy?: Prisma.ClientAccountOrderByWithRelationInput | Prisma.ClientAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientAccounts.
   */
  cursor?: Prisma.ClientAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientAccounts.
   */
  distinct?: Prisma.ClientAccountScalarFieldEnum | Prisma.ClientAccountScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount findFirstOrThrow
 */
export type ClientAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * Filter, which ClientAccount to fetch.
   */
  where?: Prisma.ClientAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAccounts to fetch.
   */
  orderBy?: Prisma.ClientAccountOrderByWithRelationInput | Prisma.ClientAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientAccounts.
   */
  cursor?: Prisma.ClientAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientAccounts.
   */
  distinct?: Prisma.ClientAccountScalarFieldEnum | Prisma.ClientAccountScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount findMany
 */
export type ClientAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * Filter, which ClientAccounts to fetch.
   */
  where?: Prisma.ClientAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAccounts to fetch.
   */
  orderBy?: Prisma.ClientAccountOrderByWithRelationInput | Prisma.ClientAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ClientAccounts.
   */
  cursor?: Prisma.ClientAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientAccounts.
   */
  distinct?: Prisma.ClientAccountScalarFieldEnum | Prisma.ClientAccountScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount create
 */
export type ClientAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a ClientAccount.
   */
  data: Prisma.XOR<Prisma.ClientAccountCreateInput, Prisma.ClientAccountUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount createMany
 */
export type ClientAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ClientAccounts.
   */
  data: Prisma.ClientAccountCreateManyInput | Prisma.ClientAccountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClientAccount update
 */
export type ClientAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a ClientAccount.
   */
  data: Prisma.XOR<Prisma.ClientAccountUpdateInput, Prisma.ClientAccountUncheckedUpdateInput>
  /**
   * Choose, which ClientAccount to update.
   */
  where: Prisma.ClientAccountWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount updateMany
 */
export type ClientAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ClientAccounts.
   */
  data: Prisma.XOR<Prisma.ClientAccountUpdateManyMutationInput, Prisma.ClientAccountUncheckedUpdateManyInput>
  /**
   * Filter which ClientAccounts to update
   */
  where?: Prisma.ClientAccountWhereInput
  /**
   * Limit how many ClientAccounts to update.
   */
  limit?: number
}

/**
 * ClientAccount upsert
 */
export type ClientAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the ClientAccount to update in case it exists.
   */
  where: Prisma.ClientAccountWhereUniqueInput
  /**
   * In case the ClientAccount found by the `where` argument doesn't exist, create a new ClientAccount with this data.
   */
  create: Prisma.XOR<Prisma.ClientAccountCreateInput, Prisma.ClientAccountUncheckedCreateInput>
  /**
   * In case the ClientAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClientAccountUpdateInput, Prisma.ClientAccountUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount delete
 */
export type ClientAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
  /**
   * Filter which ClientAccount to delete.
   */
  where: Prisma.ClientAccountWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * ClientAccount deleteMany
 */
export type ClientAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientAccounts to delete
   */
  where?: Prisma.ClientAccountWhereInput
  /**
   * Limit how many ClientAccounts to delete.
   */
  limit?: number
}

/**
 * ClientAccount.appointments
 */
export type ClientAccount$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  where?: Prisma.AppointmentWhereInput
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  cursor?: Prisma.AppointmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * ClientAccount without action
 */
export type ClientAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAccount
   */
  select?: Prisma.ClientAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAccount
   */
  omit?: Prisma.ClientAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAccountInclude<ExtArgs> | null
}
