
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DoctorSpecialization` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DoctorSpecialization
 * 
 */
export type DoctorSpecializationModel = runtime.Types.Result.DefaultSelection<Prisma.$DoctorSpecializationPayload>

export type AggregateDoctorSpecialization = {
  _count: DoctorSpecializationCountAggregateOutputType | null
  _avg: DoctorSpecializationAvgAggregateOutputType | null
  _sum: DoctorSpecializationSumAggregateOutputType | null
  _min: DoctorSpecializationMinAggregateOutputType | null
  _max: DoctorSpecializationMaxAggregateOutputType | null
}

export type DoctorSpecializationAvgAggregateOutputType = {
  id: number | null
  doctorId: number | null
  specializationId: number | null
}

export type DoctorSpecializationSumAggregateOutputType = {
  id: number | null
  doctorId: number | null
  specializationId: number | null
}

export type DoctorSpecializationMinAggregateOutputType = {
  id: number | null
  doctorId: number | null
  specializationId: number | null
}

export type DoctorSpecializationMaxAggregateOutputType = {
  id: number | null
  doctorId: number | null
  specializationId: number | null
}

export type DoctorSpecializationCountAggregateOutputType = {
  id: number
  doctorId: number
  specializationId: number
  _all: number
}


export type DoctorSpecializationAvgAggregateInputType = {
  id?: true
  doctorId?: true
  specializationId?: true
}

export type DoctorSpecializationSumAggregateInputType = {
  id?: true
  doctorId?: true
  specializationId?: true
}

export type DoctorSpecializationMinAggregateInputType = {
  id?: true
  doctorId?: true
  specializationId?: true
}

export type DoctorSpecializationMaxAggregateInputType = {
  id?: true
  doctorId?: true
  specializationId?: true
}

export type DoctorSpecializationCountAggregateInputType = {
  id?: true
  doctorId?: true
  specializationId?: true
  _all?: true
}

export type DoctorSpecializationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DoctorSpecialization to aggregate.
   */
  where?: Prisma.DoctorSpecializationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DoctorSpecializations to fetch.
   */
  orderBy?: Prisma.DoctorSpecializationOrderByWithRelationInput | Prisma.DoctorSpecializationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DoctorSpecializationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DoctorSpecializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DoctorSpecializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DoctorSpecializations
  **/
  _count?: true | DoctorSpecializationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DoctorSpecializationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DoctorSpecializationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DoctorSpecializationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DoctorSpecializationMaxAggregateInputType
}

export type GetDoctorSpecializationAggregateType<T extends DoctorSpecializationAggregateArgs> = {
      [P in keyof T & keyof AggregateDoctorSpecialization]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDoctorSpecialization[P]>
    : Prisma.GetScalarType<T[P], AggregateDoctorSpecialization[P]>
}




export type DoctorSpecializationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DoctorSpecializationWhereInput
  orderBy?: Prisma.DoctorSpecializationOrderByWithAggregationInput | Prisma.DoctorSpecializationOrderByWithAggregationInput[]
  by: Prisma.DoctorSpecializationScalarFieldEnum[] | Prisma.DoctorSpecializationScalarFieldEnum
  having?: Prisma.DoctorSpecializationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DoctorSpecializationCountAggregateInputType | true
  _avg?: DoctorSpecializationAvgAggregateInputType
  _sum?: DoctorSpecializationSumAggregateInputType
  _min?: DoctorSpecializationMinAggregateInputType
  _max?: DoctorSpecializationMaxAggregateInputType
}

export type DoctorSpecializationGroupByOutputType = {
  id: number
  doctorId: number
  specializationId: number
  _count: DoctorSpecializationCountAggregateOutputType | null
  _avg: DoctorSpecializationAvgAggregateOutputType | null
  _sum: DoctorSpecializationSumAggregateOutputType | null
  _min: DoctorSpecializationMinAggregateOutputType | null
  _max: DoctorSpecializationMaxAggregateOutputType | null
}

type GetDoctorSpecializationGroupByPayload<T extends DoctorSpecializationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DoctorSpecializationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DoctorSpecializationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DoctorSpecializationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DoctorSpecializationGroupByOutputType[P]>
      }
    >
  >



export type DoctorSpecializationWhereInput = {
  AND?: Prisma.DoctorSpecializationWhereInput | Prisma.DoctorSpecializationWhereInput[]
  OR?: Prisma.DoctorSpecializationWhereInput[]
  NOT?: Prisma.DoctorSpecializationWhereInput | Prisma.DoctorSpecializationWhereInput[]
  id?: Prisma.IntFilter<"DoctorSpecialization"> | number
  doctorId?: Prisma.IntFilter<"DoctorSpecialization"> | number
  specializationId?: Prisma.IntFilter<"DoctorSpecialization"> | number
  doctor?: Prisma.XOR<Prisma.DoctorScalarRelationFilter, Prisma.DoctorWhereInput>
  specialization?: Prisma.XOR<Prisma.SpecializationScalarRelationFilter, Prisma.SpecializationWhereInput>
}

export type DoctorSpecializationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  doctorId?: Prisma.SortOrder
  specializationId?: Prisma.SortOrder
  doctor?: Prisma.DoctorOrderByWithRelationInput
  specialization?: Prisma.SpecializationOrderByWithRelationInput
}

export type DoctorSpecializationWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.DoctorSpecializationWhereInput | Prisma.DoctorSpecializationWhereInput[]
  OR?: Prisma.DoctorSpecializationWhereInput[]
  NOT?: Prisma.DoctorSpecializationWhereInput | Prisma.DoctorSpecializationWhereInput[]
  doctorId?: Prisma.IntFilter<"DoctorSpecialization"> | number
  specializationId?: Prisma.IntFilter<"DoctorSpecialization"> | number
  doctor?: Prisma.XOR<Prisma.DoctorScalarRelationFilter, Prisma.DoctorWhereInput>
  specialization?: Prisma.XOR<Prisma.SpecializationScalarRelationFilter, Prisma.SpecializationWhereInput>
}, "id">

export type DoctorSpecializationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  doctorId?: Prisma.SortOrder
  specializationId?: Prisma.SortOrder
  _count?: Prisma.DoctorSpecializationCountOrderByAggregateInput
  _avg?: Prisma.DoctorSpecializationAvgOrderByAggregateInput
  _max?: Prisma.DoctorSpecializationMaxOrderByAggregateInput
  _min?: Prisma.DoctorSpecializationMinOrderByAggregateInput
  _sum?: Prisma.DoctorSpecializationSumOrderByAggregateInput
}

export type DoctorSpecializationScalarWhereWithAggregatesInput = {
  AND?: Prisma.DoctorSpecializationScalarWhereWithAggregatesInput | Prisma.DoctorSpecializationScalarWhereWithAggregatesInput[]
  OR?: Prisma.DoctorSpecializationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DoctorSpecializationScalarWhereWithAggregatesInput | Prisma.DoctorSpecializationScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"DoctorSpecialization"> | number
  doctorId?: Prisma.IntWithAggregatesFilter<"DoctorSpecialization"> | number
  specializationId?: Prisma.IntWithAggregatesFilter<"DoctorSpecialization"> | number
}

export type DoctorSpecializationCreateInput = {
  doctor: Prisma.DoctorCreateNestedOneWithoutSpecializationsInput
  specialization: Prisma.SpecializationCreateNestedOneWithoutDoctorsInput
}

export type DoctorSpecializationUncheckedCreateInput = {
  id?: number
  doctorId: number
  specializationId: number
}

export type DoctorSpecializationUpdateInput = {
  doctor?: Prisma.DoctorUpdateOneRequiredWithoutSpecializationsNestedInput
  specialization?: Prisma.SpecializationUpdateOneRequiredWithoutDoctorsNestedInput
}

export type DoctorSpecializationUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  doctorId?: Prisma.IntFieldUpdateOperationsInput | number
  specializationId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DoctorSpecializationCreateManyInput = {
  id?: number
  doctorId: number
  specializationId: number
}

export type DoctorSpecializationUpdateManyMutationInput = {

}

export type DoctorSpecializationUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  doctorId?: Prisma.IntFieldUpdateOperationsInput | number
  specializationId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DoctorSpecializationListRelationFilter = {
  every?: Prisma.DoctorSpecializationWhereInput
  some?: Prisma.DoctorSpecializationWhereInput
  none?: Prisma.DoctorSpecializationWhereInput
}

export type DoctorSpecializationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DoctorSpecializationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  doctorId?: Prisma.SortOrder
  specializationId?: Prisma.SortOrder
}

export type DoctorSpecializationAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  doctorId?: Prisma.SortOrder
  specializationId?: Prisma.SortOrder
}

export type DoctorSpecializationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  doctorId?: Prisma.SortOrder
  specializationId?: Prisma.SortOrder
}

export type DoctorSpecializationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  doctorId?: Prisma.SortOrder
  specializationId?: Prisma.SortOrder
}

export type DoctorSpecializationSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  doctorId?: Prisma.SortOrder
  specializationId?: Prisma.SortOrder
}

export type DoctorSpecializationCreateNestedManyWithoutDoctorInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput> | Prisma.DoctorSpecializationCreateWithoutDoctorInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput | Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput[]
  createMany?: Prisma.DoctorSpecializationCreateManyDoctorInputEnvelope
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
}

export type DoctorSpecializationUncheckedCreateNestedManyWithoutDoctorInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput> | Prisma.DoctorSpecializationCreateWithoutDoctorInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput | Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput[]
  createMany?: Prisma.DoctorSpecializationCreateManyDoctorInputEnvelope
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
}

export type DoctorSpecializationUpdateManyWithoutDoctorNestedInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput> | Prisma.DoctorSpecializationCreateWithoutDoctorInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput | Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput[]
  upsert?: Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutDoctorInput | Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutDoctorInput[]
  createMany?: Prisma.DoctorSpecializationCreateManyDoctorInputEnvelope
  set?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  disconnect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  delete?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  update?: Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutDoctorInput | Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutDoctorInput[]
  updateMany?: Prisma.DoctorSpecializationUpdateManyWithWhereWithoutDoctorInput | Prisma.DoctorSpecializationUpdateManyWithWhereWithoutDoctorInput[]
  deleteMany?: Prisma.DoctorSpecializationScalarWhereInput | Prisma.DoctorSpecializationScalarWhereInput[]
}

export type DoctorSpecializationUncheckedUpdateManyWithoutDoctorNestedInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput> | Prisma.DoctorSpecializationCreateWithoutDoctorInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput | Prisma.DoctorSpecializationCreateOrConnectWithoutDoctorInput[]
  upsert?: Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutDoctorInput | Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutDoctorInput[]
  createMany?: Prisma.DoctorSpecializationCreateManyDoctorInputEnvelope
  set?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  disconnect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  delete?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  update?: Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutDoctorInput | Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutDoctorInput[]
  updateMany?: Prisma.DoctorSpecializationUpdateManyWithWhereWithoutDoctorInput | Prisma.DoctorSpecializationUpdateManyWithWhereWithoutDoctorInput[]
  deleteMany?: Prisma.DoctorSpecializationScalarWhereInput | Prisma.DoctorSpecializationScalarWhereInput[]
}

export type DoctorSpecializationCreateNestedManyWithoutSpecializationInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput> | Prisma.DoctorSpecializationCreateWithoutSpecializationInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput | Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput[]
  createMany?: Prisma.DoctorSpecializationCreateManySpecializationInputEnvelope
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
}

export type DoctorSpecializationUncheckedCreateNestedManyWithoutSpecializationInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput> | Prisma.DoctorSpecializationCreateWithoutSpecializationInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput | Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput[]
  createMany?: Prisma.DoctorSpecializationCreateManySpecializationInputEnvelope
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
}

export type DoctorSpecializationUpdateManyWithoutSpecializationNestedInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput> | Prisma.DoctorSpecializationCreateWithoutSpecializationInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput | Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput[]
  upsert?: Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutSpecializationInput | Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutSpecializationInput[]
  createMany?: Prisma.DoctorSpecializationCreateManySpecializationInputEnvelope
  set?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  disconnect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  delete?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  update?: Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutSpecializationInput | Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutSpecializationInput[]
  updateMany?: Prisma.DoctorSpecializationUpdateManyWithWhereWithoutSpecializationInput | Prisma.DoctorSpecializationUpdateManyWithWhereWithoutSpecializationInput[]
  deleteMany?: Prisma.DoctorSpecializationScalarWhereInput | Prisma.DoctorSpecializationScalarWhereInput[]
}

export type DoctorSpecializationUncheckedUpdateManyWithoutSpecializationNestedInput = {
  create?: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput> | Prisma.DoctorSpecializationCreateWithoutSpecializationInput[] | Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput[]
  connectOrCreate?: Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput | Prisma.DoctorSpecializationCreateOrConnectWithoutSpecializationInput[]
  upsert?: Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutSpecializationInput | Prisma.DoctorSpecializationUpsertWithWhereUniqueWithoutSpecializationInput[]
  createMany?: Prisma.DoctorSpecializationCreateManySpecializationInputEnvelope
  set?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  disconnect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  delete?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  connect?: Prisma.DoctorSpecializationWhereUniqueInput | Prisma.DoctorSpecializationWhereUniqueInput[]
  update?: Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutSpecializationInput | Prisma.DoctorSpecializationUpdateWithWhereUniqueWithoutSpecializationInput[]
  updateMany?: Prisma.DoctorSpecializationUpdateManyWithWhereWithoutSpecializationInput | Prisma.DoctorSpecializationUpdateManyWithWhereWithoutSpecializationInput[]
  deleteMany?: Prisma.DoctorSpecializationScalarWhereInput | Prisma.DoctorSpecializationScalarWhereInput[]
}

export type DoctorSpecializationCreateWithoutDoctorInput = {
  specialization: Prisma.SpecializationCreateNestedOneWithoutDoctorsInput
}

export type DoctorSpecializationUncheckedCreateWithoutDoctorInput = {
  id?: number
  specializationId: number
}

export type DoctorSpecializationCreateOrConnectWithoutDoctorInput = {
  where: Prisma.DoctorSpecializationWhereUniqueInput
  create: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput>
}

export type DoctorSpecializationCreateManyDoctorInputEnvelope = {
  data: Prisma.DoctorSpecializationCreateManyDoctorInput | Prisma.DoctorSpecializationCreateManyDoctorInput[]
  skipDuplicates?: boolean
}

export type DoctorSpecializationUpsertWithWhereUniqueWithoutDoctorInput = {
  where: Prisma.DoctorSpecializationWhereUniqueInput
  update: Prisma.XOR<Prisma.DoctorSpecializationUpdateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedUpdateWithoutDoctorInput>
  create: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedCreateWithoutDoctorInput>
}

export type DoctorSpecializationUpdateWithWhereUniqueWithoutDoctorInput = {
  where: Prisma.DoctorSpecializationWhereUniqueInput
  data: Prisma.XOR<Prisma.DoctorSpecializationUpdateWithoutDoctorInput, Prisma.DoctorSpecializationUncheckedUpdateWithoutDoctorInput>
}

export type DoctorSpecializationUpdateManyWithWhereWithoutDoctorInput = {
  where: Prisma.DoctorSpecializationScalarWhereInput
  data: Prisma.XOR<Prisma.DoctorSpecializationUpdateManyMutationInput, Prisma.DoctorSpecializationUncheckedUpdateManyWithoutDoctorInput>
}

export type DoctorSpecializationScalarWhereInput = {
  AND?: Prisma.DoctorSpecializationScalarWhereInput | Prisma.DoctorSpecializationScalarWhereInput[]
  OR?: Prisma.DoctorSpecializationScalarWhereInput[]
  NOT?: Prisma.DoctorSpecializationScalarWhereInput | Prisma.DoctorSpecializationScalarWhereInput[]
  id?: Prisma.IntFilter<"DoctorSpecialization"> | number
  doctorId?: Prisma.IntFilter<"DoctorSpecialization"> | number
  specializationId?: Prisma.IntFilter<"DoctorSpecialization"> | number
}

export type DoctorSpecializationCreateWithoutSpecializationInput = {
  doctor: Prisma.DoctorCreateNestedOneWithoutSpecializationsInput
}

export type DoctorSpecializationUncheckedCreateWithoutSpecializationInput = {
  id?: number
  doctorId: number
}

export type DoctorSpecializationCreateOrConnectWithoutSpecializationInput = {
  where: Prisma.DoctorSpecializationWhereUniqueInput
  create: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput>
}

export type DoctorSpecializationCreateManySpecializationInputEnvelope = {
  data: Prisma.DoctorSpecializationCreateManySpecializationInput | Prisma.DoctorSpecializationCreateManySpecializationInput[]
  skipDuplicates?: boolean
}

export type DoctorSpecializationUpsertWithWhereUniqueWithoutSpecializationInput = {
  where: Prisma.DoctorSpecializationWhereUniqueInput
  update: Prisma.XOR<Prisma.DoctorSpecializationUpdateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedUpdateWithoutSpecializationInput>
  create: Prisma.XOR<Prisma.DoctorSpecializationCreateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedCreateWithoutSpecializationInput>
}

export type DoctorSpecializationUpdateWithWhereUniqueWithoutSpecializationInput = {
  where: Prisma.DoctorSpecializationWhereUniqueInput
  data: Prisma.XOR<Prisma.DoctorSpecializationUpdateWithoutSpecializationInput, Prisma.DoctorSpecializationUncheckedUpdateWithoutSpecializationInput>
}

export type DoctorSpecializationUpdateManyWithWhereWithoutSpecializationInput = {
  where: Prisma.DoctorSpecializationScalarWhereInput
  data: Prisma.XOR<Prisma.DoctorSpecializationUpdateManyMutationInput, Prisma.DoctorSpecializationUncheckedUpdateManyWithoutSpecializationInput>
}

export type DoctorSpecializationCreateManyDoctorInput = {
  id?: number
  specializationId: number
}

export type DoctorSpecializationUpdateWithoutDoctorInput = {
  specialization?: Prisma.SpecializationUpdateOneRequiredWithoutDoctorsNestedInput
}

export type DoctorSpecializationUncheckedUpdateWithoutDoctorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  specializationId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DoctorSpecializationUncheckedUpdateManyWithoutDoctorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  specializationId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DoctorSpecializationCreateManySpecializationInput = {
  id?: number
  doctorId: number
}

export type DoctorSpecializationUpdateWithoutSpecializationInput = {
  doctor?: Prisma.DoctorUpdateOneRequiredWithoutSpecializationsNestedInput
}

export type DoctorSpecializationUncheckedUpdateWithoutSpecializationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  doctorId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DoctorSpecializationUncheckedUpdateManyWithoutSpecializationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  doctorId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type DoctorSpecializationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  doctorId?: boolean
  specializationId?: boolean
  doctor?: boolean | Prisma.DoctorDefaultArgs<ExtArgs>
  specialization?: boolean | Prisma.SpecializationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["doctorSpecialization"]>



export type DoctorSpecializationSelectScalar = {
  id?: boolean
  doctorId?: boolean
  specializationId?: boolean
}

export type DoctorSpecializationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "doctorId" | "specializationId", ExtArgs["result"]["doctorSpecialization"]>
export type DoctorSpecializationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctor?: boolean | Prisma.DoctorDefaultArgs<ExtArgs>
  specialization?: boolean | Prisma.SpecializationDefaultArgs<ExtArgs>
}

export type $DoctorSpecializationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DoctorSpecialization"
  objects: {
    doctor: Prisma.$DoctorPayload<ExtArgs>
    specialization: Prisma.$SpecializationPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    doctorId: number
    specializationId: number
  }, ExtArgs["result"]["doctorSpecialization"]>
  composites: {}
}

export type DoctorSpecializationGetPayload<S extends boolean | null | undefined | DoctorSpecializationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload, S>

export type DoctorSpecializationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DoctorSpecializationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: DoctorSpecializationCountAggregateInputType | true
  }

export interface DoctorSpecializationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DoctorSpecialization'], meta: { name: 'DoctorSpecialization' } }
  /**
   * Find zero or one DoctorSpecialization that matches the filter.
   * @param {DoctorSpecializationFindUniqueArgs} args - Arguments to find a DoctorSpecialization
   * @example
   * // Get one DoctorSpecialization
   * const doctorSpecialization = await prisma.doctorSpecialization.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DoctorSpecializationFindUniqueArgs>(args: Prisma.SelectSubset<T, DoctorSpecializationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DoctorSpecialization that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DoctorSpecializationFindUniqueOrThrowArgs} args - Arguments to find a DoctorSpecialization
   * @example
   * // Get one DoctorSpecialization
   * const doctorSpecialization = await prisma.doctorSpecialization.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DoctorSpecializationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DoctorSpecializationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DoctorSpecialization that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorSpecializationFindFirstArgs} args - Arguments to find a DoctorSpecialization
   * @example
   * // Get one DoctorSpecialization
   * const doctorSpecialization = await prisma.doctorSpecialization.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DoctorSpecializationFindFirstArgs>(args?: Prisma.SelectSubset<T, DoctorSpecializationFindFirstArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DoctorSpecialization that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorSpecializationFindFirstOrThrowArgs} args - Arguments to find a DoctorSpecialization
   * @example
   * // Get one DoctorSpecialization
   * const doctorSpecialization = await prisma.doctorSpecialization.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DoctorSpecializationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DoctorSpecializationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DoctorSpecializations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorSpecializationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DoctorSpecializations
   * const doctorSpecializations = await prisma.doctorSpecialization.findMany()
   * 
   * // Get first 10 DoctorSpecializations
   * const doctorSpecializations = await prisma.doctorSpecialization.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const doctorSpecializationWithIdOnly = await prisma.doctorSpecialization.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DoctorSpecializationFindManyArgs>(args?: Prisma.SelectSubset<T, DoctorSpecializationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DoctorSpecialization.
   * @param {DoctorSpecializationCreateArgs} args - Arguments to create a DoctorSpecialization.
   * @example
   * // Create one DoctorSpecialization
   * const DoctorSpecialization = await prisma.doctorSpecialization.create({
   *   data: {
   *     // ... data to create a DoctorSpecialization
   *   }
   * })
   * 
   */
  create<T extends DoctorSpecializationCreateArgs>(args: Prisma.SelectSubset<T, DoctorSpecializationCreateArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DoctorSpecializations.
   * @param {DoctorSpecializationCreateManyArgs} args - Arguments to create many DoctorSpecializations.
   * @example
   * // Create many DoctorSpecializations
   * const doctorSpecialization = await prisma.doctorSpecialization.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DoctorSpecializationCreateManyArgs>(args?: Prisma.SelectSubset<T, DoctorSpecializationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DoctorSpecialization.
   * @param {DoctorSpecializationDeleteArgs} args - Arguments to delete one DoctorSpecialization.
   * @example
   * // Delete one DoctorSpecialization
   * const DoctorSpecialization = await prisma.doctorSpecialization.delete({
   *   where: {
   *     // ... filter to delete one DoctorSpecialization
   *   }
   * })
   * 
   */
  delete<T extends DoctorSpecializationDeleteArgs>(args: Prisma.SelectSubset<T, DoctorSpecializationDeleteArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DoctorSpecialization.
   * @param {DoctorSpecializationUpdateArgs} args - Arguments to update one DoctorSpecialization.
   * @example
   * // Update one DoctorSpecialization
   * const doctorSpecialization = await prisma.doctorSpecialization.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DoctorSpecializationUpdateArgs>(args: Prisma.SelectSubset<T, DoctorSpecializationUpdateArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DoctorSpecializations.
   * @param {DoctorSpecializationDeleteManyArgs} args - Arguments to filter DoctorSpecializations to delete.
   * @example
   * // Delete a few DoctorSpecializations
   * const { count } = await prisma.doctorSpecialization.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DoctorSpecializationDeleteManyArgs>(args?: Prisma.SelectSubset<T, DoctorSpecializationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DoctorSpecializations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorSpecializationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DoctorSpecializations
   * const doctorSpecialization = await prisma.doctorSpecialization.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DoctorSpecializationUpdateManyArgs>(args: Prisma.SelectSubset<T, DoctorSpecializationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DoctorSpecialization.
   * @param {DoctorSpecializationUpsertArgs} args - Arguments to update or create a DoctorSpecialization.
   * @example
   * // Update or create a DoctorSpecialization
   * const doctorSpecialization = await prisma.doctorSpecialization.upsert({
   *   create: {
   *     // ... data to create a DoctorSpecialization
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DoctorSpecialization we want to update
   *   }
   * })
   */
  upsert<T extends DoctorSpecializationUpsertArgs>(args: Prisma.SelectSubset<T, DoctorSpecializationUpsertArgs<ExtArgs>>): Prisma.Prisma__DoctorSpecializationClient<runtime.Types.Result.GetResult<Prisma.$DoctorSpecializationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DoctorSpecializations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorSpecializationCountArgs} args - Arguments to filter DoctorSpecializations to count.
   * @example
   * // Count the number of DoctorSpecializations
   * const count = await prisma.doctorSpecialization.count({
   *   where: {
   *     // ... the filter for the DoctorSpecializations we want to count
   *   }
   * })
  **/
  count<T extends DoctorSpecializationCountArgs>(
    args?: Prisma.Subset<T, DoctorSpecializationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DoctorSpecializationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DoctorSpecialization.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorSpecializationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DoctorSpecializationAggregateArgs>(args: Prisma.Subset<T, DoctorSpecializationAggregateArgs>): Prisma.PrismaPromise<GetDoctorSpecializationAggregateType<T>>

  /**
   * Group by DoctorSpecialization.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorSpecializationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DoctorSpecializationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DoctorSpecializationGroupByArgs['orderBy'] }
      : { orderBy?: DoctorSpecializationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DoctorSpecializationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDoctorSpecializationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DoctorSpecialization model
 */
readonly fields: DoctorSpecializationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DoctorSpecialization.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DoctorSpecializationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  doctor<T extends Prisma.DoctorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DoctorDefaultArgs<ExtArgs>>): Prisma.Prisma__DoctorClient<runtime.Types.Result.GetResult<Prisma.$DoctorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  specialization<T extends Prisma.SpecializationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SpecializationDefaultArgs<ExtArgs>>): Prisma.Prisma__SpecializationClient<runtime.Types.Result.GetResult<Prisma.$SpecializationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DoctorSpecialization model
 */
export interface DoctorSpecializationFieldRefs {
  readonly id: Prisma.FieldRef<"DoctorSpecialization", 'Int'>
  readonly doctorId: Prisma.FieldRef<"DoctorSpecialization", 'Int'>
  readonly specializationId: Prisma.FieldRef<"DoctorSpecialization", 'Int'>
}
    

// Custom InputTypes
/**
 * DoctorSpecialization findUnique
 */
export type DoctorSpecializationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * Filter, which DoctorSpecialization to fetch.
   */
  where: Prisma.DoctorSpecializationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization findUniqueOrThrow
 */
export type DoctorSpecializationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * Filter, which DoctorSpecialization to fetch.
   */
  where: Prisma.DoctorSpecializationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization findFirst
 */
export type DoctorSpecializationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * Filter, which DoctorSpecialization to fetch.
   */
  where?: Prisma.DoctorSpecializationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DoctorSpecializations to fetch.
   */
  orderBy?: Prisma.DoctorSpecializationOrderByWithRelationInput | Prisma.DoctorSpecializationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DoctorSpecializations.
   */
  cursor?: Prisma.DoctorSpecializationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DoctorSpecializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DoctorSpecializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DoctorSpecializations.
   */
  distinct?: Prisma.DoctorSpecializationScalarFieldEnum | Prisma.DoctorSpecializationScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization findFirstOrThrow
 */
export type DoctorSpecializationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * Filter, which DoctorSpecialization to fetch.
   */
  where?: Prisma.DoctorSpecializationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DoctorSpecializations to fetch.
   */
  orderBy?: Prisma.DoctorSpecializationOrderByWithRelationInput | Prisma.DoctorSpecializationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DoctorSpecializations.
   */
  cursor?: Prisma.DoctorSpecializationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DoctorSpecializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DoctorSpecializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DoctorSpecializations.
   */
  distinct?: Prisma.DoctorSpecializationScalarFieldEnum | Prisma.DoctorSpecializationScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization findMany
 */
export type DoctorSpecializationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * Filter, which DoctorSpecializations to fetch.
   */
  where?: Prisma.DoctorSpecializationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DoctorSpecializations to fetch.
   */
  orderBy?: Prisma.DoctorSpecializationOrderByWithRelationInput | Prisma.DoctorSpecializationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DoctorSpecializations.
   */
  cursor?: Prisma.DoctorSpecializationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DoctorSpecializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DoctorSpecializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DoctorSpecializations.
   */
  distinct?: Prisma.DoctorSpecializationScalarFieldEnum | Prisma.DoctorSpecializationScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization create
 */
export type DoctorSpecializationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * The data needed to create a DoctorSpecialization.
   */
  data: Prisma.XOR<Prisma.DoctorSpecializationCreateInput, Prisma.DoctorSpecializationUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization createMany
 */
export type DoctorSpecializationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DoctorSpecializations.
   */
  data: Prisma.DoctorSpecializationCreateManyInput | Prisma.DoctorSpecializationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DoctorSpecialization update
 */
export type DoctorSpecializationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * The data needed to update a DoctorSpecialization.
   */
  data: Prisma.XOR<Prisma.DoctorSpecializationUpdateInput, Prisma.DoctorSpecializationUncheckedUpdateInput>
  /**
   * Choose, which DoctorSpecialization to update.
   */
  where: Prisma.DoctorSpecializationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization updateMany
 */
export type DoctorSpecializationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DoctorSpecializations.
   */
  data: Prisma.XOR<Prisma.DoctorSpecializationUpdateManyMutationInput, Prisma.DoctorSpecializationUncheckedUpdateManyInput>
  /**
   * Filter which DoctorSpecializations to update
   */
  where?: Prisma.DoctorSpecializationWhereInput
  /**
   * Limit how many DoctorSpecializations to update.
   */
  limit?: number
}

/**
 * DoctorSpecialization upsert
 */
export type DoctorSpecializationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * The filter to search for the DoctorSpecialization to update in case it exists.
   */
  where: Prisma.DoctorSpecializationWhereUniqueInput
  /**
   * In case the DoctorSpecialization found by the `where` argument doesn't exist, create a new DoctorSpecialization with this data.
   */
  create: Prisma.XOR<Prisma.DoctorSpecializationCreateInput, Prisma.DoctorSpecializationUncheckedCreateInput>
  /**
   * In case the DoctorSpecialization was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DoctorSpecializationUpdateInput, Prisma.DoctorSpecializationUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization delete
 */
export type DoctorSpecializationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
  /**
   * Filter which DoctorSpecialization to delete.
   */
  where: Prisma.DoctorSpecializationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * DoctorSpecialization deleteMany
 */
export type DoctorSpecializationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DoctorSpecializations to delete
   */
  where?: Prisma.DoctorSpecializationWhereInput
  /**
   * Limit how many DoctorSpecializations to delete.
   */
  limit?: number
}

/**
 * DoctorSpecialization without action
 */
export type DoctorSpecializationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorSpecialization
   */
  select?: Prisma.DoctorSpecializationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DoctorSpecialization
   */
  omit?: Prisma.DoctorSpecializationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DoctorSpecializationInclude<ExtArgs> | null
}
