
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InNetworkInsurance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InNetworkInsurance
 * 
 */
export type InNetworkInsuranceModel = runtime.Types.Result.DefaultSelection<Prisma.$InNetworkInsurancePayload>

export type AggregateInNetworkInsurance = {
  _count: InNetworkInsuranceCountAggregateOutputType | null
  _avg: InNetworkInsuranceAvgAggregateOutputType | null
  _sum: InNetworkInsuranceSumAggregateOutputType | null
  _min: InNetworkInsuranceMinAggregateOutputType | null
  _max: InNetworkInsuranceMaxAggregateOutputType | null
}

export type InNetworkInsuranceAvgAggregateOutputType = {
  id: number | null
  officeId: number | null
}

export type InNetworkInsuranceSumAggregateOutputType = {
  id: number | null
  officeId: number | null
}

export type InNetworkInsuranceMinAggregateOutputType = {
  id: number | null
  officeId: number | null
  insuranceName: string | null
}

export type InNetworkInsuranceMaxAggregateOutputType = {
  id: number | null
  officeId: number | null
  insuranceName: string | null
}

export type InNetworkInsuranceCountAggregateOutputType = {
  id: number
  officeId: number
  insuranceName: number
  _all: number
}


export type InNetworkInsuranceAvgAggregateInputType = {
  id?: true
  officeId?: true
}

export type InNetworkInsuranceSumAggregateInputType = {
  id?: true
  officeId?: true
}

export type InNetworkInsuranceMinAggregateInputType = {
  id?: true
  officeId?: true
  insuranceName?: true
}

export type InNetworkInsuranceMaxAggregateInputType = {
  id?: true
  officeId?: true
  insuranceName?: true
}

export type InNetworkInsuranceCountAggregateInputType = {
  id?: true
  officeId?: true
  insuranceName?: true
  _all?: true
}

export type InNetworkInsuranceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InNetworkInsurance to aggregate.
   */
  where?: Prisma.InNetworkInsuranceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InNetworkInsurances to fetch.
   */
  orderBy?: Prisma.InNetworkInsuranceOrderByWithRelationInput | Prisma.InNetworkInsuranceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InNetworkInsuranceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InNetworkInsurances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InNetworkInsurances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InNetworkInsurances
  **/
  _count?: true | InNetworkInsuranceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InNetworkInsuranceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InNetworkInsuranceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InNetworkInsuranceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InNetworkInsuranceMaxAggregateInputType
}

export type GetInNetworkInsuranceAggregateType<T extends InNetworkInsuranceAggregateArgs> = {
      [P in keyof T & keyof AggregateInNetworkInsurance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInNetworkInsurance[P]>
    : Prisma.GetScalarType<T[P], AggregateInNetworkInsurance[P]>
}




export type InNetworkInsuranceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InNetworkInsuranceWhereInput
  orderBy?: Prisma.InNetworkInsuranceOrderByWithAggregationInput | Prisma.InNetworkInsuranceOrderByWithAggregationInput[]
  by: Prisma.InNetworkInsuranceScalarFieldEnum[] | Prisma.InNetworkInsuranceScalarFieldEnum
  having?: Prisma.InNetworkInsuranceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InNetworkInsuranceCountAggregateInputType | true
  _avg?: InNetworkInsuranceAvgAggregateInputType
  _sum?: InNetworkInsuranceSumAggregateInputType
  _min?: InNetworkInsuranceMinAggregateInputType
  _max?: InNetworkInsuranceMaxAggregateInputType
}

export type InNetworkInsuranceGroupByOutputType = {
  id: number
  officeId: number
  insuranceName: string
  _count: InNetworkInsuranceCountAggregateOutputType | null
  _avg: InNetworkInsuranceAvgAggregateOutputType | null
  _sum: InNetworkInsuranceSumAggregateOutputType | null
  _min: InNetworkInsuranceMinAggregateOutputType | null
  _max: InNetworkInsuranceMaxAggregateOutputType | null
}

type GetInNetworkInsuranceGroupByPayload<T extends InNetworkInsuranceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InNetworkInsuranceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InNetworkInsuranceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InNetworkInsuranceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InNetworkInsuranceGroupByOutputType[P]>
      }
    >
  >



export type InNetworkInsuranceWhereInput = {
  AND?: Prisma.InNetworkInsuranceWhereInput | Prisma.InNetworkInsuranceWhereInput[]
  OR?: Prisma.InNetworkInsuranceWhereInput[]
  NOT?: Prisma.InNetworkInsuranceWhereInput | Prisma.InNetworkInsuranceWhereInput[]
  id?: Prisma.IntFilter<"InNetworkInsurance"> | number
  officeId?: Prisma.IntFilter<"InNetworkInsurance"> | number
  insuranceName?: Prisma.StringFilter<"InNetworkInsurance"> | string
  office?: Prisma.XOR<Prisma.OfficeScalarRelationFilter, Prisma.OfficeWhereInput>
}

export type InNetworkInsuranceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  insuranceName?: Prisma.SortOrder
  office?: Prisma.OfficeOrderByWithRelationInput
  _relevance?: Prisma.InNetworkInsuranceOrderByRelevanceInput
}

export type InNetworkInsuranceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.InNetworkInsuranceWhereInput | Prisma.InNetworkInsuranceWhereInput[]
  OR?: Prisma.InNetworkInsuranceWhereInput[]
  NOT?: Prisma.InNetworkInsuranceWhereInput | Prisma.InNetworkInsuranceWhereInput[]
  officeId?: Prisma.IntFilter<"InNetworkInsurance"> | number
  insuranceName?: Prisma.StringFilter<"InNetworkInsurance"> | string
  office?: Prisma.XOR<Prisma.OfficeScalarRelationFilter, Prisma.OfficeWhereInput>
}, "id">

export type InNetworkInsuranceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  insuranceName?: Prisma.SortOrder
  _count?: Prisma.InNetworkInsuranceCountOrderByAggregateInput
  _avg?: Prisma.InNetworkInsuranceAvgOrderByAggregateInput
  _max?: Prisma.InNetworkInsuranceMaxOrderByAggregateInput
  _min?: Prisma.InNetworkInsuranceMinOrderByAggregateInput
  _sum?: Prisma.InNetworkInsuranceSumOrderByAggregateInput
}

export type InNetworkInsuranceScalarWhereWithAggregatesInput = {
  AND?: Prisma.InNetworkInsuranceScalarWhereWithAggregatesInput | Prisma.InNetworkInsuranceScalarWhereWithAggregatesInput[]
  OR?: Prisma.InNetworkInsuranceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InNetworkInsuranceScalarWhereWithAggregatesInput | Prisma.InNetworkInsuranceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"InNetworkInsurance"> | number
  officeId?: Prisma.IntWithAggregatesFilter<"InNetworkInsurance"> | number
  insuranceName?: Prisma.StringWithAggregatesFilter<"InNetworkInsurance"> | string
}

export type InNetworkInsuranceCreateInput = {
  insuranceName: string
  office: Prisma.OfficeCreateNestedOneWithoutInsurancesInput
}

export type InNetworkInsuranceUncheckedCreateInput = {
  id?: number
  officeId: number
  insuranceName: string
}

export type InNetworkInsuranceUpdateInput = {
  insuranceName?: Prisma.StringFieldUpdateOperationsInput | string
  office?: Prisma.OfficeUpdateOneRequiredWithoutInsurancesNestedInput
}

export type InNetworkInsuranceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  officeId?: Prisma.IntFieldUpdateOperationsInput | number
  insuranceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type InNetworkInsuranceCreateManyInput = {
  id?: number
  officeId: number
  insuranceName: string
}

export type InNetworkInsuranceUpdateManyMutationInput = {
  insuranceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type InNetworkInsuranceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  officeId?: Prisma.IntFieldUpdateOperationsInput | number
  insuranceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type InNetworkInsuranceListRelationFilter = {
  every?: Prisma.InNetworkInsuranceWhereInput
  some?: Prisma.InNetworkInsuranceWhereInput
  none?: Prisma.InNetworkInsuranceWhereInput
}

export type InNetworkInsuranceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InNetworkInsuranceOrderByRelevanceInput = {
  fields: Prisma.InNetworkInsuranceOrderByRelevanceFieldEnum | Prisma.InNetworkInsuranceOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type InNetworkInsuranceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  insuranceName?: Prisma.SortOrder
}

export type InNetworkInsuranceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
}

export type InNetworkInsuranceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  insuranceName?: Prisma.SortOrder
}

export type InNetworkInsuranceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  insuranceName?: Prisma.SortOrder
}

export type InNetworkInsuranceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
}

export type InNetworkInsuranceCreateNestedManyWithoutOfficeInput = {
  create?: Prisma.XOR<Prisma.InNetworkInsuranceCreateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput> | Prisma.InNetworkInsuranceCreateWithoutOfficeInput[] | Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput | Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput[]
  createMany?: Prisma.InNetworkInsuranceCreateManyOfficeInputEnvelope
  connect?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
}

export type InNetworkInsuranceUncheckedCreateNestedManyWithoutOfficeInput = {
  create?: Prisma.XOR<Prisma.InNetworkInsuranceCreateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput> | Prisma.InNetworkInsuranceCreateWithoutOfficeInput[] | Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput | Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput[]
  createMany?: Prisma.InNetworkInsuranceCreateManyOfficeInputEnvelope
  connect?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
}

export type InNetworkInsuranceUpdateManyWithoutOfficeNestedInput = {
  create?: Prisma.XOR<Prisma.InNetworkInsuranceCreateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput> | Prisma.InNetworkInsuranceCreateWithoutOfficeInput[] | Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput | Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput[]
  upsert?: Prisma.InNetworkInsuranceUpsertWithWhereUniqueWithoutOfficeInput | Prisma.InNetworkInsuranceUpsertWithWhereUniqueWithoutOfficeInput[]
  createMany?: Prisma.InNetworkInsuranceCreateManyOfficeInputEnvelope
  set?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  disconnect?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  delete?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  connect?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  update?: Prisma.InNetworkInsuranceUpdateWithWhereUniqueWithoutOfficeInput | Prisma.InNetworkInsuranceUpdateWithWhereUniqueWithoutOfficeInput[]
  updateMany?: Prisma.InNetworkInsuranceUpdateManyWithWhereWithoutOfficeInput | Prisma.InNetworkInsuranceUpdateManyWithWhereWithoutOfficeInput[]
  deleteMany?: Prisma.InNetworkInsuranceScalarWhereInput | Prisma.InNetworkInsuranceScalarWhereInput[]
}

export type InNetworkInsuranceUncheckedUpdateManyWithoutOfficeNestedInput = {
  create?: Prisma.XOR<Prisma.InNetworkInsuranceCreateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput> | Prisma.InNetworkInsuranceCreateWithoutOfficeInput[] | Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput | Prisma.InNetworkInsuranceCreateOrConnectWithoutOfficeInput[]
  upsert?: Prisma.InNetworkInsuranceUpsertWithWhereUniqueWithoutOfficeInput | Prisma.InNetworkInsuranceUpsertWithWhereUniqueWithoutOfficeInput[]
  createMany?: Prisma.InNetworkInsuranceCreateManyOfficeInputEnvelope
  set?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  disconnect?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  delete?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  connect?: Prisma.InNetworkInsuranceWhereUniqueInput | Prisma.InNetworkInsuranceWhereUniqueInput[]
  update?: Prisma.InNetworkInsuranceUpdateWithWhereUniqueWithoutOfficeInput | Prisma.InNetworkInsuranceUpdateWithWhereUniqueWithoutOfficeInput[]
  updateMany?: Prisma.InNetworkInsuranceUpdateManyWithWhereWithoutOfficeInput | Prisma.InNetworkInsuranceUpdateManyWithWhereWithoutOfficeInput[]
  deleteMany?: Prisma.InNetworkInsuranceScalarWhereInput | Prisma.InNetworkInsuranceScalarWhereInput[]
}

export type InNetworkInsuranceCreateWithoutOfficeInput = {
  insuranceName: string
}

export type InNetworkInsuranceUncheckedCreateWithoutOfficeInput = {
  id?: number
  insuranceName: string
}

export type InNetworkInsuranceCreateOrConnectWithoutOfficeInput = {
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  create: Prisma.XOR<Prisma.InNetworkInsuranceCreateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput>
}

export type InNetworkInsuranceCreateManyOfficeInputEnvelope = {
  data: Prisma.InNetworkInsuranceCreateManyOfficeInput | Prisma.InNetworkInsuranceCreateManyOfficeInput[]
  skipDuplicates?: boolean
}

export type InNetworkInsuranceUpsertWithWhereUniqueWithoutOfficeInput = {
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  update: Prisma.XOR<Prisma.InNetworkInsuranceUpdateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedUpdateWithoutOfficeInput>
  create: Prisma.XOR<Prisma.InNetworkInsuranceCreateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedCreateWithoutOfficeInput>
}

export type InNetworkInsuranceUpdateWithWhereUniqueWithoutOfficeInput = {
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  data: Prisma.XOR<Prisma.InNetworkInsuranceUpdateWithoutOfficeInput, Prisma.InNetworkInsuranceUncheckedUpdateWithoutOfficeInput>
}

export type InNetworkInsuranceUpdateManyWithWhereWithoutOfficeInput = {
  where: Prisma.InNetworkInsuranceScalarWhereInput
  data: Prisma.XOR<Prisma.InNetworkInsuranceUpdateManyMutationInput, Prisma.InNetworkInsuranceUncheckedUpdateManyWithoutOfficeInput>
}

export type InNetworkInsuranceScalarWhereInput = {
  AND?: Prisma.InNetworkInsuranceScalarWhereInput | Prisma.InNetworkInsuranceScalarWhereInput[]
  OR?: Prisma.InNetworkInsuranceScalarWhereInput[]
  NOT?: Prisma.InNetworkInsuranceScalarWhereInput | Prisma.InNetworkInsuranceScalarWhereInput[]
  id?: Prisma.IntFilter<"InNetworkInsurance"> | number
  officeId?: Prisma.IntFilter<"InNetworkInsurance"> | number
  insuranceName?: Prisma.StringFilter<"InNetworkInsurance"> | string
}

export type InNetworkInsuranceCreateManyOfficeInput = {
  id?: number
  insuranceName: string
}

export type InNetworkInsuranceUpdateWithoutOfficeInput = {
  insuranceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type InNetworkInsuranceUncheckedUpdateWithoutOfficeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  insuranceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type InNetworkInsuranceUncheckedUpdateManyWithoutOfficeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  insuranceName?: Prisma.StringFieldUpdateOperationsInput | string
}



export type InNetworkInsuranceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  officeId?: boolean
  insuranceName?: boolean
  office?: boolean | Prisma.OfficeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inNetworkInsurance"]>



export type InNetworkInsuranceSelectScalar = {
  id?: boolean
  officeId?: boolean
  insuranceName?: boolean
}

export type InNetworkInsuranceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "officeId" | "insuranceName", ExtArgs["result"]["inNetworkInsurance"]>
export type InNetworkInsuranceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  office?: boolean | Prisma.OfficeDefaultArgs<ExtArgs>
}

export type $InNetworkInsurancePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InNetworkInsurance"
  objects: {
    office: Prisma.$OfficePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    officeId: number
    insuranceName: string
  }, ExtArgs["result"]["inNetworkInsurance"]>
  composites: {}
}

export type InNetworkInsuranceGetPayload<S extends boolean | null | undefined | InNetworkInsuranceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload, S>

export type InNetworkInsuranceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InNetworkInsuranceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: InNetworkInsuranceCountAggregateInputType | true
  }

export interface InNetworkInsuranceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InNetworkInsurance'], meta: { name: 'InNetworkInsurance' } }
  /**
   * Find zero or one InNetworkInsurance that matches the filter.
   * @param {InNetworkInsuranceFindUniqueArgs} args - Arguments to find a InNetworkInsurance
   * @example
   * // Get one InNetworkInsurance
   * const inNetworkInsurance = await prisma.inNetworkInsurance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InNetworkInsuranceFindUniqueArgs>(args: Prisma.SelectSubset<T, InNetworkInsuranceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InNetworkInsurance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InNetworkInsuranceFindUniqueOrThrowArgs} args - Arguments to find a InNetworkInsurance
   * @example
   * // Get one InNetworkInsurance
   * const inNetworkInsurance = await prisma.inNetworkInsurance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InNetworkInsuranceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InNetworkInsuranceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InNetworkInsurance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InNetworkInsuranceFindFirstArgs} args - Arguments to find a InNetworkInsurance
   * @example
   * // Get one InNetworkInsurance
   * const inNetworkInsurance = await prisma.inNetworkInsurance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InNetworkInsuranceFindFirstArgs>(args?: Prisma.SelectSubset<T, InNetworkInsuranceFindFirstArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InNetworkInsurance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InNetworkInsuranceFindFirstOrThrowArgs} args - Arguments to find a InNetworkInsurance
   * @example
   * // Get one InNetworkInsurance
   * const inNetworkInsurance = await prisma.inNetworkInsurance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InNetworkInsuranceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InNetworkInsuranceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InNetworkInsurances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InNetworkInsuranceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InNetworkInsurances
   * const inNetworkInsurances = await prisma.inNetworkInsurance.findMany()
   * 
   * // Get first 10 InNetworkInsurances
   * const inNetworkInsurances = await prisma.inNetworkInsurance.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inNetworkInsuranceWithIdOnly = await prisma.inNetworkInsurance.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InNetworkInsuranceFindManyArgs>(args?: Prisma.SelectSubset<T, InNetworkInsuranceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InNetworkInsurance.
   * @param {InNetworkInsuranceCreateArgs} args - Arguments to create a InNetworkInsurance.
   * @example
   * // Create one InNetworkInsurance
   * const InNetworkInsurance = await prisma.inNetworkInsurance.create({
   *   data: {
   *     // ... data to create a InNetworkInsurance
   *   }
   * })
   * 
   */
  create<T extends InNetworkInsuranceCreateArgs>(args: Prisma.SelectSubset<T, InNetworkInsuranceCreateArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InNetworkInsurances.
   * @param {InNetworkInsuranceCreateManyArgs} args - Arguments to create many InNetworkInsurances.
   * @example
   * // Create many InNetworkInsurances
   * const inNetworkInsurance = await prisma.inNetworkInsurance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InNetworkInsuranceCreateManyArgs>(args?: Prisma.SelectSubset<T, InNetworkInsuranceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a InNetworkInsurance.
   * @param {InNetworkInsuranceDeleteArgs} args - Arguments to delete one InNetworkInsurance.
   * @example
   * // Delete one InNetworkInsurance
   * const InNetworkInsurance = await prisma.inNetworkInsurance.delete({
   *   where: {
   *     // ... filter to delete one InNetworkInsurance
   *   }
   * })
   * 
   */
  delete<T extends InNetworkInsuranceDeleteArgs>(args: Prisma.SelectSubset<T, InNetworkInsuranceDeleteArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InNetworkInsurance.
   * @param {InNetworkInsuranceUpdateArgs} args - Arguments to update one InNetworkInsurance.
   * @example
   * // Update one InNetworkInsurance
   * const inNetworkInsurance = await prisma.inNetworkInsurance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InNetworkInsuranceUpdateArgs>(args: Prisma.SelectSubset<T, InNetworkInsuranceUpdateArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InNetworkInsurances.
   * @param {InNetworkInsuranceDeleteManyArgs} args - Arguments to filter InNetworkInsurances to delete.
   * @example
   * // Delete a few InNetworkInsurances
   * const { count } = await prisma.inNetworkInsurance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InNetworkInsuranceDeleteManyArgs>(args?: Prisma.SelectSubset<T, InNetworkInsuranceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InNetworkInsurances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InNetworkInsuranceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InNetworkInsurances
   * const inNetworkInsurance = await prisma.inNetworkInsurance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InNetworkInsuranceUpdateManyArgs>(args: Prisma.SelectSubset<T, InNetworkInsuranceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one InNetworkInsurance.
   * @param {InNetworkInsuranceUpsertArgs} args - Arguments to update or create a InNetworkInsurance.
   * @example
   * // Update or create a InNetworkInsurance
   * const inNetworkInsurance = await prisma.inNetworkInsurance.upsert({
   *   create: {
   *     // ... data to create a InNetworkInsurance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InNetworkInsurance we want to update
   *   }
   * })
   */
  upsert<T extends InNetworkInsuranceUpsertArgs>(args: Prisma.SelectSubset<T, InNetworkInsuranceUpsertArgs<ExtArgs>>): Prisma.Prisma__InNetworkInsuranceClient<runtime.Types.Result.GetResult<Prisma.$InNetworkInsurancePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InNetworkInsurances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InNetworkInsuranceCountArgs} args - Arguments to filter InNetworkInsurances to count.
   * @example
   * // Count the number of InNetworkInsurances
   * const count = await prisma.inNetworkInsurance.count({
   *   where: {
   *     // ... the filter for the InNetworkInsurances we want to count
   *   }
   * })
  **/
  count<T extends InNetworkInsuranceCountArgs>(
    args?: Prisma.Subset<T, InNetworkInsuranceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InNetworkInsuranceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InNetworkInsurance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InNetworkInsuranceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InNetworkInsuranceAggregateArgs>(args: Prisma.Subset<T, InNetworkInsuranceAggregateArgs>): Prisma.PrismaPromise<GetInNetworkInsuranceAggregateType<T>>

  /**
   * Group by InNetworkInsurance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InNetworkInsuranceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InNetworkInsuranceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InNetworkInsuranceGroupByArgs['orderBy'] }
      : { orderBy?: InNetworkInsuranceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InNetworkInsuranceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInNetworkInsuranceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InNetworkInsurance model
 */
readonly fields: InNetworkInsuranceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InNetworkInsurance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InNetworkInsuranceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  office<T extends Prisma.OfficeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficeDefaultArgs<ExtArgs>>): Prisma.Prisma__OfficeClient<runtime.Types.Result.GetResult<Prisma.$OfficePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InNetworkInsurance model
 */
export interface InNetworkInsuranceFieldRefs {
  readonly id: Prisma.FieldRef<"InNetworkInsurance", 'Int'>
  readonly officeId: Prisma.FieldRef<"InNetworkInsurance", 'Int'>
  readonly insuranceName: Prisma.FieldRef<"InNetworkInsurance", 'String'>
}
    

// Custom InputTypes
/**
 * InNetworkInsurance findUnique
 */
export type InNetworkInsuranceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * Filter, which InNetworkInsurance to fetch.
   */
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance findUniqueOrThrow
 */
export type InNetworkInsuranceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * Filter, which InNetworkInsurance to fetch.
   */
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance findFirst
 */
export type InNetworkInsuranceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * Filter, which InNetworkInsurance to fetch.
   */
  where?: Prisma.InNetworkInsuranceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InNetworkInsurances to fetch.
   */
  orderBy?: Prisma.InNetworkInsuranceOrderByWithRelationInput | Prisma.InNetworkInsuranceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InNetworkInsurances.
   */
  cursor?: Prisma.InNetworkInsuranceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InNetworkInsurances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InNetworkInsurances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InNetworkInsurances.
   */
  distinct?: Prisma.InNetworkInsuranceScalarFieldEnum | Prisma.InNetworkInsuranceScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance findFirstOrThrow
 */
export type InNetworkInsuranceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * Filter, which InNetworkInsurance to fetch.
   */
  where?: Prisma.InNetworkInsuranceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InNetworkInsurances to fetch.
   */
  orderBy?: Prisma.InNetworkInsuranceOrderByWithRelationInput | Prisma.InNetworkInsuranceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InNetworkInsurances.
   */
  cursor?: Prisma.InNetworkInsuranceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InNetworkInsurances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InNetworkInsurances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InNetworkInsurances.
   */
  distinct?: Prisma.InNetworkInsuranceScalarFieldEnum | Prisma.InNetworkInsuranceScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance findMany
 */
export type InNetworkInsuranceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * Filter, which InNetworkInsurances to fetch.
   */
  where?: Prisma.InNetworkInsuranceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InNetworkInsurances to fetch.
   */
  orderBy?: Prisma.InNetworkInsuranceOrderByWithRelationInput | Prisma.InNetworkInsuranceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InNetworkInsurances.
   */
  cursor?: Prisma.InNetworkInsuranceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InNetworkInsurances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InNetworkInsurances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InNetworkInsurances.
   */
  distinct?: Prisma.InNetworkInsuranceScalarFieldEnum | Prisma.InNetworkInsuranceScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance create
 */
export type InNetworkInsuranceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * The data needed to create a InNetworkInsurance.
   */
  data: Prisma.XOR<Prisma.InNetworkInsuranceCreateInput, Prisma.InNetworkInsuranceUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance createMany
 */
export type InNetworkInsuranceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InNetworkInsurances.
   */
  data: Prisma.InNetworkInsuranceCreateManyInput | Prisma.InNetworkInsuranceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InNetworkInsurance update
 */
export type InNetworkInsuranceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * The data needed to update a InNetworkInsurance.
   */
  data: Prisma.XOR<Prisma.InNetworkInsuranceUpdateInput, Prisma.InNetworkInsuranceUncheckedUpdateInput>
  /**
   * Choose, which InNetworkInsurance to update.
   */
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance updateMany
 */
export type InNetworkInsuranceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InNetworkInsurances.
   */
  data: Prisma.XOR<Prisma.InNetworkInsuranceUpdateManyMutationInput, Prisma.InNetworkInsuranceUncheckedUpdateManyInput>
  /**
   * Filter which InNetworkInsurances to update
   */
  where?: Prisma.InNetworkInsuranceWhereInput
  /**
   * Limit how many InNetworkInsurances to update.
   */
  limit?: number
}

/**
 * InNetworkInsurance upsert
 */
export type InNetworkInsuranceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * The filter to search for the InNetworkInsurance to update in case it exists.
   */
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  /**
   * In case the InNetworkInsurance found by the `where` argument doesn't exist, create a new InNetworkInsurance with this data.
   */
  create: Prisma.XOR<Prisma.InNetworkInsuranceCreateInput, Prisma.InNetworkInsuranceUncheckedCreateInput>
  /**
   * In case the InNetworkInsurance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InNetworkInsuranceUpdateInput, Prisma.InNetworkInsuranceUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance delete
 */
export type InNetworkInsuranceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
  /**
   * Filter which InNetworkInsurance to delete.
   */
  where: Prisma.InNetworkInsuranceWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * InNetworkInsurance deleteMany
 */
export type InNetworkInsuranceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InNetworkInsurances to delete
   */
  where?: Prisma.InNetworkInsuranceWhereInput
  /**
   * Limit how many InNetworkInsurances to delete.
   */
  limit?: number
}

/**
 * InNetworkInsurance without action
 */
export type InNetworkInsuranceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InNetworkInsurance
   */
  select?: Prisma.InNetworkInsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InNetworkInsurance
   */
  omit?: Prisma.InNetworkInsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InNetworkInsuranceInclude<ExtArgs> | null
}
