
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TimeSlot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TimeSlot
 * 
 */
export type TimeSlotModel = runtime.Types.Result.DefaultSelection<Prisma.$TimeSlotPayload>

export type AggregateTimeSlot = {
  _count: TimeSlotCountAggregateOutputType | null
  _avg: TimeSlotAvgAggregateOutputType | null
  _sum: TimeSlotSumAggregateOutputType | null
  _min: TimeSlotMinAggregateOutputType | null
  _max: TimeSlotMaxAggregateOutputType | null
}

export type TimeSlotAvgAggregateOutputType = {
  id: number | null
  officeId: number | null
}

export type TimeSlotSumAggregateOutputType = {
  id: number | null
  officeId: number | null
}

export type TimeSlotMinAggregateOutputType = {
  id: number | null
  officeId: number | null
  startTime: Date | null
  endTime: Date | null
  isBooked: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TimeSlotMaxAggregateOutputType = {
  id: number | null
  officeId: number | null
  startTime: Date | null
  endTime: Date | null
  isBooked: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TimeSlotCountAggregateOutputType = {
  id: number
  officeId: number
  startTime: number
  endTime: number
  isBooked: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TimeSlotAvgAggregateInputType = {
  id?: true
  officeId?: true
}

export type TimeSlotSumAggregateInputType = {
  id?: true
  officeId?: true
}

export type TimeSlotMinAggregateInputType = {
  id?: true
  officeId?: true
  startTime?: true
  endTime?: true
  isBooked?: true
  createdAt?: true
  updatedAt?: true
}

export type TimeSlotMaxAggregateInputType = {
  id?: true
  officeId?: true
  startTime?: true
  endTime?: true
  isBooked?: true
  createdAt?: true
  updatedAt?: true
}

export type TimeSlotCountAggregateInputType = {
  id?: true
  officeId?: true
  startTime?: true
  endTime?: true
  isBooked?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TimeSlotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeSlot to aggregate.
   */
  where?: Prisma.TimeSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSlots to fetch.
   */
  orderBy?: Prisma.TimeSlotOrderByWithRelationInput | Prisma.TimeSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TimeSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TimeSlots
  **/
  _count?: true | TimeSlotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TimeSlotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TimeSlotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TimeSlotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TimeSlotMaxAggregateInputType
}

export type GetTimeSlotAggregateType<T extends TimeSlotAggregateArgs> = {
      [P in keyof T & keyof AggregateTimeSlot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTimeSlot[P]>
    : Prisma.GetScalarType<T[P], AggregateTimeSlot[P]>
}




export type TimeSlotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeSlotWhereInput
  orderBy?: Prisma.TimeSlotOrderByWithAggregationInput | Prisma.TimeSlotOrderByWithAggregationInput[]
  by: Prisma.TimeSlotScalarFieldEnum[] | Prisma.TimeSlotScalarFieldEnum
  having?: Prisma.TimeSlotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TimeSlotCountAggregateInputType | true
  _avg?: TimeSlotAvgAggregateInputType
  _sum?: TimeSlotSumAggregateInputType
  _min?: TimeSlotMinAggregateInputType
  _max?: TimeSlotMaxAggregateInputType
}

export type TimeSlotGroupByOutputType = {
  id: number
  officeId: number
  startTime: Date
  endTime: Date
  isBooked: boolean
  createdAt: Date
  updatedAt: Date
  _count: TimeSlotCountAggregateOutputType | null
  _avg: TimeSlotAvgAggregateOutputType | null
  _sum: TimeSlotSumAggregateOutputType | null
  _min: TimeSlotMinAggregateOutputType | null
  _max: TimeSlotMaxAggregateOutputType | null
}

type GetTimeSlotGroupByPayload<T extends TimeSlotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TimeSlotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TimeSlotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TimeSlotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TimeSlotGroupByOutputType[P]>
      }
    >
  >



export type TimeSlotWhereInput = {
  AND?: Prisma.TimeSlotWhereInput | Prisma.TimeSlotWhereInput[]
  OR?: Prisma.TimeSlotWhereInput[]
  NOT?: Prisma.TimeSlotWhereInput | Prisma.TimeSlotWhereInput[]
  id?: Prisma.IntFilter<"TimeSlot"> | number
  officeId?: Prisma.IntFilter<"TimeSlot"> | number
  startTime?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  endTime?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  isBooked?: Prisma.BoolFilter<"TimeSlot"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  office?: Prisma.XOR<Prisma.OfficeScalarRelationFilter, Prisma.OfficeWhereInput>
  appointments?: Prisma.AppointmentListRelationFilter
}

export type TimeSlotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  office?: Prisma.OfficeOrderByWithRelationInput
  appointments?: Prisma.AppointmentOrderByRelationAggregateInput
}

export type TimeSlotWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TimeSlotWhereInput | Prisma.TimeSlotWhereInput[]
  OR?: Prisma.TimeSlotWhereInput[]
  NOT?: Prisma.TimeSlotWhereInput | Prisma.TimeSlotWhereInput[]
  officeId?: Prisma.IntFilter<"TimeSlot"> | number
  startTime?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  endTime?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  isBooked?: Prisma.BoolFilter<"TimeSlot"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  office?: Prisma.XOR<Prisma.OfficeScalarRelationFilter, Prisma.OfficeWhereInput>
  appointments?: Prisma.AppointmentListRelationFilter
}, "id">

export type TimeSlotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TimeSlotCountOrderByAggregateInput
  _avg?: Prisma.TimeSlotAvgOrderByAggregateInput
  _max?: Prisma.TimeSlotMaxOrderByAggregateInput
  _min?: Prisma.TimeSlotMinOrderByAggregateInput
  _sum?: Prisma.TimeSlotSumOrderByAggregateInput
}

export type TimeSlotScalarWhereWithAggregatesInput = {
  AND?: Prisma.TimeSlotScalarWhereWithAggregatesInput | Prisma.TimeSlotScalarWhereWithAggregatesInput[]
  OR?: Prisma.TimeSlotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TimeSlotScalarWhereWithAggregatesInput | Prisma.TimeSlotScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TimeSlot"> | number
  officeId?: Prisma.IntWithAggregatesFilter<"TimeSlot"> | number
  startTime?: Prisma.DateTimeWithAggregatesFilter<"TimeSlot"> | Date | string
  endTime?: Prisma.DateTimeWithAggregatesFilter<"TimeSlot"> | Date | string
  isBooked?: Prisma.BoolWithAggregatesFilter<"TimeSlot"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TimeSlot"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TimeSlot"> | Date | string
}

export type TimeSlotCreateInput = {
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  office: Prisma.OfficeCreateNestedOneWithoutTimeSlotsInput
  appointments?: Prisma.AppointmentCreateNestedManyWithoutTimeSlotInput
}

export type TimeSlotUncheckedCreateInput = {
  id?: number
  officeId: number
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutTimeSlotInput
}

export type TimeSlotUpdateInput = {
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  office?: Prisma.OfficeUpdateOneRequiredWithoutTimeSlotsNestedInput
  appointments?: Prisma.AppointmentUpdateManyWithoutTimeSlotNestedInput
}

export type TimeSlotUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  officeId?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutTimeSlotNestedInput
}

export type TimeSlotCreateManyInput = {
  id?: number
  officeId: number
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSlotUpdateManyMutationInput = {
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSlotUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  officeId?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSlotListRelationFilter = {
  every?: Prisma.TimeSlotWhereInput
  some?: Prisma.TimeSlotWhereInput
  none?: Prisma.TimeSlotWhereInput
}

export type TimeSlotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TimeSlotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeSlotAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
}

export type TimeSlotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeSlotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  isBooked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeSlotSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  officeId?: Prisma.SortOrder
}

export type TimeSlotScalarRelationFilter = {
  is?: Prisma.TimeSlotWhereInput
  isNot?: Prisma.TimeSlotWhereInput
}

export type TimeSlotCreateNestedManyWithoutOfficeInput = {
  create?: Prisma.XOR<Prisma.TimeSlotCreateWithoutOfficeInput, Prisma.TimeSlotUncheckedCreateWithoutOfficeInput> | Prisma.TimeSlotCreateWithoutOfficeInput[] | Prisma.TimeSlotUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.TimeSlotCreateOrConnectWithoutOfficeInput | Prisma.TimeSlotCreateOrConnectWithoutOfficeInput[]
  createMany?: Prisma.TimeSlotCreateManyOfficeInputEnvelope
  connect?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
}

export type TimeSlotUncheckedCreateNestedManyWithoutOfficeInput = {
  create?: Prisma.XOR<Prisma.TimeSlotCreateWithoutOfficeInput, Prisma.TimeSlotUncheckedCreateWithoutOfficeInput> | Prisma.TimeSlotCreateWithoutOfficeInput[] | Prisma.TimeSlotUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.TimeSlotCreateOrConnectWithoutOfficeInput | Prisma.TimeSlotCreateOrConnectWithoutOfficeInput[]
  createMany?: Prisma.TimeSlotCreateManyOfficeInputEnvelope
  connect?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
}

export type TimeSlotUpdateManyWithoutOfficeNestedInput = {
  create?: Prisma.XOR<Prisma.TimeSlotCreateWithoutOfficeInput, Prisma.TimeSlotUncheckedCreateWithoutOfficeInput> | Prisma.TimeSlotCreateWithoutOfficeInput[] | Prisma.TimeSlotUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.TimeSlotCreateOrConnectWithoutOfficeInput | Prisma.TimeSlotCreateOrConnectWithoutOfficeInput[]
  upsert?: Prisma.TimeSlotUpsertWithWhereUniqueWithoutOfficeInput | Prisma.TimeSlotUpsertWithWhereUniqueWithoutOfficeInput[]
  createMany?: Prisma.TimeSlotCreateManyOfficeInputEnvelope
  set?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  disconnect?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  delete?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  connect?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  update?: Prisma.TimeSlotUpdateWithWhereUniqueWithoutOfficeInput | Prisma.TimeSlotUpdateWithWhereUniqueWithoutOfficeInput[]
  updateMany?: Prisma.TimeSlotUpdateManyWithWhereWithoutOfficeInput | Prisma.TimeSlotUpdateManyWithWhereWithoutOfficeInput[]
  deleteMany?: Prisma.TimeSlotScalarWhereInput | Prisma.TimeSlotScalarWhereInput[]
}

export type TimeSlotUncheckedUpdateManyWithoutOfficeNestedInput = {
  create?: Prisma.XOR<Prisma.TimeSlotCreateWithoutOfficeInput, Prisma.TimeSlotUncheckedCreateWithoutOfficeInput> | Prisma.TimeSlotCreateWithoutOfficeInput[] | Prisma.TimeSlotUncheckedCreateWithoutOfficeInput[]
  connectOrCreate?: Prisma.TimeSlotCreateOrConnectWithoutOfficeInput | Prisma.TimeSlotCreateOrConnectWithoutOfficeInput[]
  upsert?: Prisma.TimeSlotUpsertWithWhereUniqueWithoutOfficeInput | Prisma.TimeSlotUpsertWithWhereUniqueWithoutOfficeInput[]
  createMany?: Prisma.TimeSlotCreateManyOfficeInputEnvelope
  set?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  disconnect?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  delete?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  connect?: Prisma.TimeSlotWhereUniqueInput | Prisma.TimeSlotWhereUniqueInput[]
  update?: Prisma.TimeSlotUpdateWithWhereUniqueWithoutOfficeInput | Prisma.TimeSlotUpdateWithWhereUniqueWithoutOfficeInput[]
  updateMany?: Prisma.TimeSlotUpdateManyWithWhereWithoutOfficeInput | Prisma.TimeSlotUpdateManyWithWhereWithoutOfficeInput[]
  deleteMany?: Prisma.TimeSlotScalarWhereInput | Prisma.TimeSlotScalarWhereInput[]
}

export type TimeSlotCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.TimeSlotCreateWithoutAppointmentsInput, Prisma.TimeSlotUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.TimeSlotCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.TimeSlotWhereUniqueInput
}

export type TimeSlotUpdateOneRequiredWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.TimeSlotCreateWithoutAppointmentsInput, Prisma.TimeSlotUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.TimeSlotCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.TimeSlotUpsertWithoutAppointmentsInput
  connect?: Prisma.TimeSlotWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TimeSlotUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.TimeSlotUpdateWithoutAppointmentsInput>, Prisma.TimeSlotUncheckedUpdateWithoutAppointmentsInput>
}

export type TimeSlotCreateWithoutOfficeInput = {
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentCreateNestedManyWithoutTimeSlotInput
}

export type TimeSlotUncheckedCreateWithoutOfficeInput = {
  id?: number
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutTimeSlotInput
}

export type TimeSlotCreateOrConnectWithoutOfficeInput = {
  where: Prisma.TimeSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeSlotCreateWithoutOfficeInput, Prisma.TimeSlotUncheckedCreateWithoutOfficeInput>
}

export type TimeSlotCreateManyOfficeInputEnvelope = {
  data: Prisma.TimeSlotCreateManyOfficeInput | Prisma.TimeSlotCreateManyOfficeInput[]
  skipDuplicates?: boolean
}

export type TimeSlotUpsertWithWhereUniqueWithoutOfficeInput = {
  where: Prisma.TimeSlotWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeSlotUpdateWithoutOfficeInput, Prisma.TimeSlotUncheckedUpdateWithoutOfficeInput>
  create: Prisma.XOR<Prisma.TimeSlotCreateWithoutOfficeInput, Prisma.TimeSlotUncheckedCreateWithoutOfficeInput>
}

export type TimeSlotUpdateWithWhereUniqueWithoutOfficeInput = {
  where: Prisma.TimeSlotWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeSlotUpdateWithoutOfficeInput, Prisma.TimeSlotUncheckedUpdateWithoutOfficeInput>
}

export type TimeSlotUpdateManyWithWhereWithoutOfficeInput = {
  where: Prisma.TimeSlotScalarWhereInput
  data: Prisma.XOR<Prisma.TimeSlotUpdateManyMutationInput, Prisma.TimeSlotUncheckedUpdateManyWithoutOfficeInput>
}

export type TimeSlotScalarWhereInput = {
  AND?: Prisma.TimeSlotScalarWhereInput | Prisma.TimeSlotScalarWhereInput[]
  OR?: Prisma.TimeSlotScalarWhereInput[]
  NOT?: Prisma.TimeSlotScalarWhereInput | Prisma.TimeSlotScalarWhereInput[]
  id?: Prisma.IntFilter<"TimeSlot"> | number
  officeId?: Prisma.IntFilter<"TimeSlot"> | number
  startTime?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  endTime?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  isBooked?: Prisma.BoolFilter<"TimeSlot"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TimeSlot"> | Date | string
}

export type TimeSlotCreateWithoutAppointmentsInput = {
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  office: Prisma.OfficeCreateNestedOneWithoutTimeSlotsInput
}

export type TimeSlotUncheckedCreateWithoutAppointmentsInput = {
  id?: number
  officeId: number
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSlotCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.TimeSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeSlotCreateWithoutAppointmentsInput, Prisma.TimeSlotUncheckedCreateWithoutAppointmentsInput>
}

export type TimeSlotUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.TimeSlotUpdateWithoutAppointmentsInput, Prisma.TimeSlotUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.TimeSlotCreateWithoutAppointmentsInput, Prisma.TimeSlotUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.TimeSlotWhereInput
}

export type TimeSlotUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.TimeSlotWhereInput
  data: Prisma.XOR<Prisma.TimeSlotUpdateWithoutAppointmentsInput, Prisma.TimeSlotUncheckedUpdateWithoutAppointmentsInput>
}

export type TimeSlotUpdateWithoutAppointmentsInput = {
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  office?: Prisma.OfficeUpdateOneRequiredWithoutTimeSlotsNestedInput
}

export type TimeSlotUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  officeId?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSlotCreateManyOfficeInput = {
  id?: number
  startTime: Date | string
  endTime: Date | string
  isBooked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSlotUpdateWithoutOfficeInput = {
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUpdateManyWithoutTimeSlotNestedInput
}

export type TimeSlotUncheckedUpdateWithoutOfficeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutTimeSlotNestedInput
}

export type TimeSlotUncheckedUpdateManyWithoutOfficeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isBooked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TimeSlotCountOutputType
 */

export type TimeSlotCountOutputType = {
  appointments: number
}

export type TimeSlotCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | TimeSlotCountOutputTypeCountAppointmentsArgs
}

/**
 * TimeSlotCountOutputType without action
 */
export type TimeSlotCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlotCountOutputType
   */
  select?: Prisma.TimeSlotCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TimeSlotCountOutputType without action
 */
export type TimeSlotCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentWhereInput
}


export type TimeSlotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  officeId?: boolean
  startTime?: boolean
  endTime?: boolean
  isBooked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  office?: boolean | Prisma.OfficeDefaultArgs<ExtArgs>
  appointments?: boolean | Prisma.TimeSlot$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.TimeSlotCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timeSlot"]>



export type TimeSlotSelectScalar = {
  id?: boolean
  officeId?: boolean
  startTime?: boolean
  endTime?: boolean
  isBooked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TimeSlotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "officeId" | "startTime" | "endTime" | "isBooked" | "createdAt" | "updatedAt", ExtArgs["result"]["timeSlot"]>
export type TimeSlotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  office?: boolean | Prisma.OfficeDefaultArgs<ExtArgs>
  appointments?: boolean | Prisma.TimeSlot$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.TimeSlotCountOutputTypeDefaultArgs<ExtArgs>
}

export type $TimeSlotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TimeSlot"
  objects: {
    office: Prisma.$OfficePayload<ExtArgs>
    appointments: Prisma.$AppointmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    officeId: number
    startTime: Date
    endTime: Date
    isBooked: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["timeSlot"]>
  composites: {}
}

export type TimeSlotGetPayload<S extends boolean | null | undefined | TimeSlotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload, S>

export type TimeSlotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TimeSlotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: TimeSlotCountAggregateInputType | true
  }

export interface TimeSlotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TimeSlot'], meta: { name: 'TimeSlot' } }
  /**
   * Find zero or one TimeSlot that matches the filter.
   * @param {TimeSlotFindUniqueArgs} args - Arguments to find a TimeSlot
   * @example
   * // Get one TimeSlot
   * const timeSlot = await prisma.timeSlot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TimeSlotFindUniqueArgs>(args: Prisma.SelectSubset<T, TimeSlotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TimeSlot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TimeSlotFindUniqueOrThrowArgs} args - Arguments to find a TimeSlot
   * @example
   * // Get one TimeSlot
   * const timeSlot = await prisma.timeSlot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TimeSlotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TimeSlotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeSlot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSlotFindFirstArgs} args - Arguments to find a TimeSlot
   * @example
   * // Get one TimeSlot
   * const timeSlot = await prisma.timeSlot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TimeSlotFindFirstArgs>(args?: Prisma.SelectSubset<T, TimeSlotFindFirstArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeSlot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSlotFindFirstOrThrowArgs} args - Arguments to find a TimeSlot
   * @example
   * // Get one TimeSlot
   * const timeSlot = await prisma.timeSlot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TimeSlotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TimeSlotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TimeSlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSlotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TimeSlots
   * const timeSlots = await prisma.timeSlot.findMany()
   * 
   * // Get first 10 TimeSlots
   * const timeSlots = await prisma.timeSlot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const timeSlotWithIdOnly = await prisma.timeSlot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TimeSlotFindManyArgs>(args?: Prisma.SelectSubset<T, TimeSlotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TimeSlot.
   * @param {TimeSlotCreateArgs} args - Arguments to create a TimeSlot.
   * @example
   * // Create one TimeSlot
   * const TimeSlot = await prisma.timeSlot.create({
   *   data: {
   *     // ... data to create a TimeSlot
   *   }
   * })
   * 
   */
  create<T extends TimeSlotCreateArgs>(args: Prisma.SelectSubset<T, TimeSlotCreateArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TimeSlots.
   * @param {TimeSlotCreateManyArgs} args - Arguments to create many TimeSlots.
   * @example
   * // Create many TimeSlots
   * const timeSlot = await prisma.timeSlot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TimeSlotCreateManyArgs>(args?: Prisma.SelectSubset<T, TimeSlotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a TimeSlot.
   * @param {TimeSlotDeleteArgs} args - Arguments to delete one TimeSlot.
   * @example
   * // Delete one TimeSlot
   * const TimeSlot = await prisma.timeSlot.delete({
   *   where: {
   *     // ... filter to delete one TimeSlot
   *   }
   * })
   * 
   */
  delete<T extends TimeSlotDeleteArgs>(args: Prisma.SelectSubset<T, TimeSlotDeleteArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TimeSlot.
   * @param {TimeSlotUpdateArgs} args - Arguments to update one TimeSlot.
   * @example
   * // Update one TimeSlot
   * const timeSlot = await prisma.timeSlot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TimeSlotUpdateArgs>(args: Prisma.SelectSubset<T, TimeSlotUpdateArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TimeSlots.
   * @param {TimeSlotDeleteManyArgs} args - Arguments to filter TimeSlots to delete.
   * @example
   * // Delete a few TimeSlots
   * const { count } = await prisma.timeSlot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TimeSlotDeleteManyArgs>(args?: Prisma.SelectSubset<T, TimeSlotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimeSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSlotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TimeSlots
   * const timeSlot = await prisma.timeSlot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TimeSlotUpdateManyArgs>(args: Prisma.SelectSubset<T, TimeSlotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one TimeSlot.
   * @param {TimeSlotUpsertArgs} args - Arguments to update or create a TimeSlot.
   * @example
   * // Update or create a TimeSlot
   * const timeSlot = await prisma.timeSlot.upsert({
   *   create: {
   *     // ... data to create a TimeSlot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TimeSlot we want to update
   *   }
   * })
   */
  upsert<T extends TimeSlotUpsertArgs>(args: Prisma.SelectSubset<T, TimeSlotUpsertArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TimeSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSlotCountArgs} args - Arguments to filter TimeSlots to count.
   * @example
   * // Count the number of TimeSlots
   * const count = await prisma.timeSlot.count({
   *   where: {
   *     // ... the filter for the TimeSlots we want to count
   *   }
   * })
  **/
  count<T extends TimeSlotCountArgs>(
    args?: Prisma.Subset<T, TimeSlotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TimeSlotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TimeSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSlotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TimeSlotAggregateArgs>(args: Prisma.Subset<T, TimeSlotAggregateArgs>): Prisma.PrismaPromise<GetTimeSlotAggregateType<T>>

  /**
   * Group by TimeSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSlotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TimeSlotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TimeSlotGroupByArgs['orderBy'] }
      : { orderBy?: TimeSlotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TimeSlotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTimeSlotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TimeSlot model
 */
readonly fields: TimeSlotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TimeSlot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TimeSlotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  office<T extends Prisma.OfficeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficeDefaultArgs<ExtArgs>>): Prisma.Prisma__OfficeClient<runtime.Types.Result.GetResult<Prisma.$OfficePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  appointments<T extends Prisma.TimeSlot$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TimeSlot$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TimeSlot model
 */
export interface TimeSlotFieldRefs {
  readonly id: Prisma.FieldRef<"TimeSlot", 'Int'>
  readonly officeId: Prisma.FieldRef<"TimeSlot", 'Int'>
  readonly startTime: Prisma.FieldRef<"TimeSlot", 'DateTime'>
  readonly endTime: Prisma.FieldRef<"TimeSlot", 'DateTime'>
  readonly isBooked: Prisma.FieldRef<"TimeSlot", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"TimeSlot", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TimeSlot", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TimeSlot findUnique
 */
export type TimeSlotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * Filter, which TimeSlot to fetch.
   */
  where: Prisma.TimeSlotWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot findUniqueOrThrow
 */
export type TimeSlotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * Filter, which TimeSlot to fetch.
   */
  where: Prisma.TimeSlotWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot findFirst
 */
export type TimeSlotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * Filter, which TimeSlot to fetch.
   */
  where?: Prisma.TimeSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSlots to fetch.
   */
  orderBy?: Prisma.TimeSlotOrderByWithRelationInput | Prisma.TimeSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeSlots.
   */
  cursor?: Prisma.TimeSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeSlots.
   */
  distinct?: Prisma.TimeSlotScalarFieldEnum | Prisma.TimeSlotScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot findFirstOrThrow
 */
export type TimeSlotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * Filter, which TimeSlot to fetch.
   */
  where?: Prisma.TimeSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSlots to fetch.
   */
  orderBy?: Prisma.TimeSlotOrderByWithRelationInput | Prisma.TimeSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeSlots.
   */
  cursor?: Prisma.TimeSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeSlots.
   */
  distinct?: Prisma.TimeSlotScalarFieldEnum | Prisma.TimeSlotScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot findMany
 */
export type TimeSlotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * Filter, which TimeSlots to fetch.
   */
  where?: Prisma.TimeSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSlots to fetch.
   */
  orderBy?: Prisma.TimeSlotOrderByWithRelationInput | Prisma.TimeSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TimeSlots.
   */
  cursor?: Prisma.TimeSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeSlots.
   */
  distinct?: Prisma.TimeSlotScalarFieldEnum | Prisma.TimeSlotScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot create
 */
export type TimeSlotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * The data needed to create a TimeSlot.
   */
  data: Prisma.XOR<Prisma.TimeSlotCreateInput, Prisma.TimeSlotUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot createMany
 */
export type TimeSlotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TimeSlots.
   */
  data: Prisma.TimeSlotCreateManyInput | Prisma.TimeSlotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TimeSlot update
 */
export type TimeSlotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * The data needed to update a TimeSlot.
   */
  data: Prisma.XOR<Prisma.TimeSlotUpdateInput, Prisma.TimeSlotUncheckedUpdateInput>
  /**
   * Choose, which TimeSlot to update.
   */
  where: Prisma.TimeSlotWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot updateMany
 */
export type TimeSlotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TimeSlots.
   */
  data: Prisma.XOR<Prisma.TimeSlotUpdateManyMutationInput, Prisma.TimeSlotUncheckedUpdateManyInput>
  /**
   * Filter which TimeSlots to update
   */
  where?: Prisma.TimeSlotWhereInput
  /**
   * Limit how many TimeSlots to update.
   */
  limit?: number
}

/**
 * TimeSlot upsert
 */
export type TimeSlotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * The filter to search for the TimeSlot to update in case it exists.
   */
  where: Prisma.TimeSlotWhereUniqueInput
  /**
   * In case the TimeSlot found by the `where` argument doesn't exist, create a new TimeSlot with this data.
   */
  create: Prisma.XOR<Prisma.TimeSlotCreateInput, Prisma.TimeSlotUncheckedCreateInput>
  /**
   * In case the TimeSlot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TimeSlotUpdateInput, Prisma.TimeSlotUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot delete
 */
export type TimeSlotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
  /**
   * Filter which TimeSlot to delete.
   */
  where: Prisma.TimeSlotWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TimeSlot deleteMany
 */
export type TimeSlotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeSlots to delete
   */
  where?: Prisma.TimeSlotWhereInput
  /**
   * Limit how many TimeSlots to delete.
   */
  limit?: number
}

/**
 * TimeSlot.appointments
 */
export type TimeSlot$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  where?: Prisma.AppointmentWhereInput
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  cursor?: Prisma.AppointmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * TimeSlot without action
 */
export type TimeSlotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSlot
   */
  select?: Prisma.TimeSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSlot
   */
  omit?: Prisma.TimeSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSlotInclude<ExtArgs> | null
}
